//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJ_CAIS.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MJ_CAIS.Common.Resources.ApplicationResources", typeof(ApplicationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ново заявление.
        /// </summary>
        public static string btnNewApp {
            get {
                return ResourceManager.GetString("btnNewApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прехвърлено от електронно заявление.
        /// </summary>
        public static string descApplicationFromWeb {
            get {
                return ResourceManager.GetString("descApplicationFromWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одобрено електронно заявление.
        /// </summary>
        public static string descAprovedApp {
            get {
                return ResourceManager.GetString("descAprovedApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очаква от съдия избор на бюлетини, съобразно целта и избор на подписващи.
        /// </summary>
        public static string descChangeStatus {
            get {
                return ResourceManager.GetString("descChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данни от заявление.
        /// </summary>
        public static string lblAppInfo {
            get {
                return ResourceManager.GetString("lblAppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на заявяване.
        /// </summary>
        public static string lblCreatedOn {
            get {
                return ResourceManager.GetString("lblCreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бюро съдимост.
        /// </summary>
        public static string lblCsAuthorityId {
            get {
                return ResourceManager.GetString("lblCsAuthorityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕГН.
        /// </summary>
        public static string lblEgn {
            get {
                return ResourceManager.GetString("lblEgn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна поща.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Плащане.
        /// </summary>
        public static string lblIsPaid {
            get {
                return ResourceManager.GetString("lblIsPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имена.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начин на плащане.
        /// </summary>
        public static string lblPaymentMethodId {
            get {
                return ResourceManager.GetString("lblPaymentMethodId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание на целта.
        /// </summary>
        public static string lblPurpose {
            get {
                return ResourceManager.GetString("lblPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цел.
        /// </summary>
        public static string lblPurposeId {
            get {
                return ResourceManager.GetString("lblPurposeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получаване.
        /// </summary>
        public static string lblReceiving {
            get {
                return ResourceManager.GetString("lblReceiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чрез ССЕВ - Система за сигурно електронно връчване.
        /// </summary>
        public static string lblReceivingEDelivery {
            get {
                return ResourceManager.GetString("lblReceivingEDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to От този портал.
        /// </summary>
        public static string lblReceivingFromPortal {
            get {
                return ResourceManager.GetString("lblReceivingFromPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрационен номер.
        /// </summary>
        public static string lblRegistrationNumber {
            get {
                return ResourceManager.GetString("lblRegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешно създадено заявление.
        /// </summary>
        public static string messageCreateSuccessfull {
            get {
                return ResourceManager.GetString("messageCreateSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При избор на &quot;Освободено от плащане&quot; трябва да прикачите документ удостоверяващ това право..
        /// </summary>
        public static string msgPaymentFreeInfo {
            get {
                return ResourceManager.GetString("msgPaymentFreeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За да се обработи заявката, е необходимо в 14-дневен срок да заплатите държавна такса за издаване на свидетелство за съдимост в размер на 3.00 лв..
        /// </summary>
        public static string msgPaymentInfo {
            get {
                return ResourceManager.GetString("msgPaymentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявления.
        /// </summary>
        public static string titleApplications {
            get {
                return ResourceManager.GetString("titleApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Издадени свидетелства.
        /// </summary>
        public static string titleApplicationsForStatistics {
            get {
                return ResourceManager.GetString("titleApplicationsForStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявление за издаване на електронно свидетелство за съдимост.
        /// </summary>
        public static string titleAppPreview {
            get {
                return ResourceManager.GetString("titleAppPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърдено плащане.
        /// </summary>
        public static string titleConfirmedPayment {
            get {
                return ResourceManager.GetString("titleConfirmedPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свали свидетелство.
        /// </summary>
        public static string titleDownloadCertificate {
            get {
                return ResourceManager.GetString("titleDownloadCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ново заявление.
        /// </summary>
        public static string titleNewApp {
            get {
                return ResourceManager.GetString("titleNewApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Издадени справки.
        /// </summary>
        public static string titleReportsForStatistics {
            get {
                return ResourceManager.GetString("titleReportsForStatistics", resourceCulture);
            }
        }
    }
}
