//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJ_CAIS.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MJ_CAIS.Common.Resources.ReportResources", typeof(ReportResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Държава на раждане.
        /// </summary>
        public static string lblBirthCountry {
            get {
                return ResourceManager.GetString("lblBirthCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string lblBirthdate {
            get {
                return ResourceManager.GetString("lblBirthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата на раждане.
        /// </summary>
        public static string lblBirthDatePrec {
            get {
                return ResourceManager.GetString("lblBirthDatePrec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Място на раждане.
        /// </summary>
        public static string lblBirthPlace {
            get {
                return ResourceManager.GetString("lblBirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕГН.
        /// </summary>
        public static string lblEgn {
            get {
                return ResourceManager.GetString("lblEgn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string lblFamilyname {
            get {
                return ResourceManager.GetString("lblFamilyname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string lblFirstName {
            get {
                return ResourceManager.GetString("lblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пълно име.
        /// </summary>
        public static string lblFullname {
            get {
                return ResourceManager.GetString("lblFullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор.
        /// </summary>
        public static string lblIdentifier {
            get {
                return ResourceManager.GetString("lblIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатори.
        /// </summary>
        public static string lblIdentifiers {
            get {
                return ResourceManager.GetString("lblIdentifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип идентификатор.
        /// </summary>
        public static string lblIdentifierType {
            get {
                return ResourceManager.GetString("lblIdentifierType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правно основание.
        /// </summary>
        public static string lblLawReason {
            get {
                return ResourceManager.GetString("lblLawReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЛНЧ.
        /// </summary>
        public static string lblLnch {
            get {
                return ResourceManager.GetString("lblLnch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бележки.
        /// </summary>
        public static string lblRemark {
            get {
                return ResourceManager.GetString("lblRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Презиме.
        /// </summary>
        public static string lblSurname {
            get {
                return ResourceManager.GetString("lblSurname", resourceCulture);
            }
        }
    }
}
