//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJ_CAIS.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UsersResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsersResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MJ_CAIS.Common.Resources.UsersResources", typeof(UsersResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов потребител.
        /// </summary>
        public static string btnCreateNewUser {
            get {
                return ResourceManager.GetString("btnCreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активен.
        /// </summary>
        public static string lblActive {
            get {
                return ResourceManager.GetString("lblActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администрация.
        /// </summary>
        public static string lblAdministration {
            get {
                return ResourceManager.GetString("lblAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потвърждение на парола.
        /// </summary>
        public static string lblConfirmPassword {
            get {
                return ResourceManager.GetString("lblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕГН.
        /// </summary>
        public static string lblEgn {
            get {
                return ResourceManager.GetString("lblEgn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна поща.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активен.
        /// </summary>
        public static string lblIsActive {
            get {
                return ResourceManager.GetString("lblIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор.
        /// </summary>
        public static string lblIsAdmin {
            get {
                return ResourceManager.GetString("lblIsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имена.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позиция.
        /// </summary>
        public static string lblPosition {
            get {
                return ResourceManager.GetString("lblPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име.
        /// </summary>
        public static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Успешна промяна на парола!.
        /// </summary>
        public static string msgPasswordChangeSuccess {
            get {
                return ResourceManager.GetString("msgPasswordChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неуспешна промяна на парола!.
        /// </summary>
        public static string msgPasswordChangeUnsuccess {
            get {
                return ResourceManager.GetString("msgPasswordChangeUnsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата изисква цифра.
        /// </summary>
        public static string msgPasswordRequiresDigit {
            get {
                return ResourceManager.GetString("msgPasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата изисква малка буква.
        /// </summary>
        public static string msgPasswordRequiresLower {
            get {
                return ResourceManager.GetString("msgPasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата изисква специален символ.
        /// </summary>
        public static string msgPasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("msgPasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата изисква главна буква.
        /// </summary>
        public static string msgPasswordRequiresUpper {
            get {
                return ResourceManager.GetString("msgPasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролите трябва да съвпадат.
        /// </summary>
        public static string msgPasswordsMustMatch {
            get {
                return ResourceManager.GetString("msgPasswordsMustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата е прекалено къса.
        /// </summary>
        public static string msgPasswordTooShort {
            get {
                return ResourceManager.GetString("msgPasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавяне на потребител.
        /// </summary>
        public static string titleAddUser {
            get {
                return ResourceManager.GetString("titleAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редакция на потребител.
        /// </summary>
        public static string titleEditUser {
            get {
                return ResourceManager.GetString("titleEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преглед на потребител.
        /// </summary>
        public static string titlePreviewUser {
            get {
                return ResourceManager.GetString("titlePreviewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребители.
        /// </summary>
        public static string titleUsers {
            get {
                return ResourceManager.GetString("titleUsers", resourceCulture);
            }
        }
    }
}
