<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2008 rel. 2 sp1 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xdt="http://www.w3.org/2005/xpath-datatypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:altova="http://www.altova.com">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.0 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:template match="/">
		<html>
			<head>
				<title/>
			</head>
			<body>
				<xsl:for-each select="$XML">
					<h3 align="center">
						<span>
							<xsl:text>Национална агенция по приходите</xsl:text>
						</span>
					</h3>
					<h2 align="center">
						<span>
							<xsl:text>Справка с данни за осигурените лица от подадени декларации по Наредба Н-13 към Кодекса за социално осигуряване</xsl:text>
						</span>
					</h2>
					<xsl:for-each select="GetSocialSecurityDataFromDeclarationsResponse">
						<xsl:for-each select="SocialSecurityDataFromDeclarations">
							<xsl:for-each select="SocialSecurityDataFromDeclaration">
								<xsl:for-each select="DeclarationType">
									<br/>
									<span style="font-weight:bold; ">
										<xsl:text>Вид на декларацията: </xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<xsl:for-each select="PersonIdentifier">
									<br/>
									<span style="font-weight:bold; ">
										<xsl:text>Идентификатор на осигуреното лице: </xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<xsl:for-each select="PersonLastNameAndInitials">
									<br/>
									<span style="font-weight:bold; ">
										<xsl:text>Инициали и фамилия на осигуреното лице:</xsl:text>
									</span>
									<span>
										<xsl:text>&#160;</xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<xsl:for-each select="InsurerIdentifier">
									<br/>
									<span style="font-weight:bold; ">
										<xsl:text>Идентификатор на осигурител:</xsl:text>
									</span>
									<span>
										<xsl:text>&#160;</xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<xsl:for-each select="InsurerName">
									<br/>
									<span style="font-weight:bold; ">
										<xsl:text>Наименование на осигурител:</xsl:text>
									</span>
									<span>
										<xsl:text>&#160;</xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<xsl:for-each select="InsurerAdress">
									<br/>
									<span style="font-weight:bold; ">
										<xsl:text>Адрес на осигурителя: </xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<xsl:for-each select="Month">
									<br/>
									<span style="font-weight:bold; ">
										<xsl:text>Месец: </xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<xsl:for-each select="Year">
									<br/>
									<span style="font-weight:bold; ">
										<xsl:text>Година: </xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<xsl:for-each select="PersonType">
									<br/>
									<span style="font-weight:bold; ">
										<xsl:text>Вид осигурен: </xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<xsl:for-each select="TotalInsuredDays">
									<br/>
									<span style="font-weight:bold; ">
										<xsl:text>Дни в осигуряване – общо:</xsl:text>
									</span>
									<span>
										<xsl:text>&#160;</xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<xsl:for-each select="DaysWorked">
									<br/>
									<span style="font-weight:bold; ">
										<xsl:text>Отработени дни: </xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<xsl:for-each select="LawEstablishedWorkHours">
									<br/>
									<span style="font-weight:bold; ">
										<xsl:text>Законоустановено работно време:</xsl:text>
									</span>
									<span>
										<xsl:text>&#160;</xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<xsl:for-each select="DailyAgreedWorkHours">
									<br/>
									<span style="font-weight:bold; ">
										<xsl:text>Дневно договорено работно време:</xsl:text>
									</span>
									<span>
										<xsl:text>&#160;</xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<xsl:for-each select="SocialSecurityIncome">
									<br/>
									<span style="font-weight:bold; ">
										<xsl:text>Осигурителен доход:</xsl:text>
									</span>
									<span>
										<xsl:text>&#160;</xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<xsl:for-each select="GVRSFundFlag">
									<br/>
									<span style="font-weight:bold; ">
										<xsl:text>Флаг фонд ГВРС:</xsl:text>
									</span>
									<span>
										<xsl:text>&#160;</xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<xsl:for-each select="CorrectionCode">
									<br/>
									<span style="font-weight:bold; ">
										<xsl:text>Код на корекция:</xsl:text>
									</span>
									<span>
										<xsl:text>&#160;</xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<xsl:for-each select="SubmissionDate">
									<br/>
									<span style="font-weight:bold; ">
										<xsl:text>Дата на подаване:</xsl:text>
									</span>
									<span>
										<xsl:text>&#160;</xsl:text>
									</span>
									<span>
										<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00')"/>
										<xsl:text>.</xsl:text>
										<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00')"/>
										<xsl:text>.</xsl:text>
										<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000')"/>
									</span>
								</xsl:for-each>
								<h4>
									<span>
										<xsl:text>Данни от заявката:</xsl:text>
									</span>
								</h4>
								<xsl:for-each select="RequestPersonIdentifier">
									<span style="font-weight:bold; text-decoration:underline; ">
										<xsl:text>Тип на идентификатор за физическо лице:</xsl:text>
									</span>
									<span>
										<xsl:text>&#160;</xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<br/>
								<xsl:for-each select="RequestPersonIdentifierType">
									<span style="font-weight:bold; text-decoration:underline; ">
										<xsl:text>Тип на идентификатор на физическо лице: </xsl:text>
									</span>
									<xsl:choose>
										<xsl:when test=". = &apos;EGN&apos;">
											<span style="font-weight:bold; ">
												<xsl:text>ЕГН</xsl:text>
											</span>
										</xsl:when>
										<xsl:when test=". =&apos;LNCh&apos;">
											<span style="font-weight:bold; ">
												<xsl:text>ЛНЧ</xsl:text>
											</span>
										</xsl:when>
										<xsl:when test=". =&apos;NRASystemNo&apos;">
											<span style="font-weight:bold; ">
												<xsl:text>Служебен номер от регистъра на НАП</xsl:text>
											</span>
										</xsl:when>
										<xsl:when test=". =&apos;EIK_BULSTAT&apos;">
											<span style="font-weight:bold; ">
												<xsl:text>ЕИК по БУЛСТАТ</xsl:text>
											</span>
										</xsl:when>
									</xsl:choose>
								</xsl:for-each>
								<br/>
								<xsl:for-each select="RequestInsurerIdentificator">
									<span>
										<xsl:text>&#160;</xsl:text>
									</span>
									<span style="font-weight:bold; text-decoration:underline; ">
										<xsl:text>Идентификатор на осигурителя:</xsl:text>
									</span>
									<span>
										<xsl:text>&#160;</xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<br/>
								<xsl:for-each select="RequestMonthFrom">
									<span style="font-weight:bold; text-decoration:underline; ">
										<xsl:text>Месец от: </xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<br/>
								<xsl:for-each select="RequestYearFrom">
									<span style="font-weight:bold; text-decoration:underline; ">
										<xsl:text>Година от: </xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<br/>
								<xsl:for-each select="RequestMonthTo">
									<span style="font-weight:bold; text-decoration:underline; ">
										<xsl:text>Месец до: </xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<br/>
								<xsl:for-each select="RequestYearTo">
									<span style="font-weight:bold; text-decoration:underline; ">
										<xsl:text>Година до: </xsl:text>
									</span>
									<xsl:apply-templates/>
								</xsl:for-each>
								<br/>
								<hr/>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</xsl:for-each>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
