<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2008 rel. 2 sp1 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:n1="http://egov.bg/RegiX/NRA/SocialSecurityDataFromDeclarations/Request" xmlns:xdt="http://www.w3.org/2005/xpath-datatypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:altova="http://www.altova.com">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.0 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:template match="/">
		<html>
			<head>
				<title/>
			</head>
			<body>
				<xsl:for-each select="$XML">
					<h3 align="center">
						<span>
							<xsl:text>Входни параметри на Справка с данни за осигурените лица от подадени декларации по Наредба Н-13 към Кодекса за социално осигуряване</xsl:text>
						</span>
					</h3>
					<xsl:for-each select="n1:GetSocialSecurityDataFromDeclarationsRequest">
						<br/>
						<xsl:for-each select="n1:PersonIdentifier">
							<span style="font-style:italic; ">
								<xsl:text>Идентификатор за осигуреното физическо лице – с ограничение до 10 разряда:</xsl:text>
							</span>
							<span>
								<xsl:text>&#160;</xsl:text>
							</span>
							<span style="font-weight:bold; ">
								<xsl:apply-templates/>
							</span>
						</xsl:for-each>
						<br/>
						<xsl:for-each select="n1:PersonIdentifierType">
							<span style="font-style:italic; ">
								<xsl:text>Тип на идентификатор на физическо лице:</xsl:text>
							</span>
							<span>
								<xsl:text>&#160;</xsl:text>
							</span>
							<xsl:choose>
								<xsl:when test=". = &apos;EGN&apos;">
									<span style="font-weight:bold; ">
										<xsl:text>ЕГН</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test=". =&apos;LNCh&apos;">
									<span style="font-weight:bold; ">
										<xsl:text>ЛНЧ</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test=". =&apos;NRASystemNo&apos;">
									<span style="font-weight:bold; ">
										<xsl:text>Служебен номер от регистъра на НАП</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test=". =&apos;EIK_BULSTAT&apos;">
									<span style="font-weight:bold; ">
										<xsl:text>ЕИК по БУЛСТАТ</xsl:text>
									</span>
								</xsl:when>
							</xsl:choose>
						</xsl:for-each>
						<br/>
						<xsl:for-each select="n1:InsurerIdentificator">
							<span style="font-style:italic; ">
								<xsl:text>Идентификатор на осигурителя (ЕИК/сл.№ от регистъра на НАП)</xsl:text>
							</span>
							<span>
								<xsl:text>: </xsl:text>
							</span>
							<span style="font-weight:bold; ">
								<xsl:apply-templates/>
							</span>
						</xsl:for-each>
						<br/>
						<xsl:for-each select="n1:MonthFrom">
							<span style="font-style:italic; ">
								<xsl:text>Месец от: </xsl:text>
							</span>
							<xsl:choose>
								<xsl:when test="contains(   .   , 05 )">
									<span style="font-weight:bold; ">
										<xsl:text>май</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , 06 )">
									<span style="font-weight:bold; ">
										<xsl:text>юни</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , 04 )">
									<span style="font-weight:bold; ">
										<xsl:text>април</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , 03 )">
									<span style="font-weight:bold; ">
										<xsl:text>март</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , &apos;02&apos; )">
									<span style="font-weight:bold; ">
										<xsl:text>февруари</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , &apos;01&apos;)">
									<span style="font-weight:bold; ">
										<xsl:text>януари</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , 07 )">
									<span style="font-weight:bold; ">
										<xsl:text>юли</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , 08 )">
									<span style="font-weight:bold; ">
										<xsl:text>август</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , 09 )">
									<span style="font-weight:bold; ">
										<xsl:text>септември</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , 10)">
									<span style="font-weight:bold; ">
										<xsl:text>октомври</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , 11 )">
									<span style="font-weight:bold; ">
										<xsl:text>ноември</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , 12 )">
									<span style="font-weight:bold; ">
										<xsl:text>декември</xsl:text>
									</span>
								</xsl:when>
							</xsl:choose>
						</xsl:for-each>
						<br/>
						<xsl:for-each select="n1:YearFrom">
							<span style="font-style:italic; ">
								<xsl:text>Година от:</xsl:text>
							</span>
							<span>
								<xsl:text>&#160;</xsl:text>
							</span>
							<span style="font-weight:bold; ">
								<xsl:apply-templates/>
							</span>
						</xsl:for-each>
						<br/>
						<xsl:for-each select="n1:MonthTo">
							<span style="font-style:italic; ">
								<xsl:text>Месец до: </xsl:text>
							</span>
							<xsl:choose>
								<xsl:when test="contains(   .   , 05 )">
									<span style="font-weight:bold; ">
										<xsl:text>май</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , 06 )">
									<span style="font-weight:bold; ">
										<xsl:text>юни</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , 04 )">
									<span style="font-weight:bold; ">
										<xsl:text>април</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , 03 )">
									<span style="font-weight:bold; ">
										<xsl:text>март</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , &apos;02&apos; )">
									<span style="font-weight:bold; ">
										<xsl:text>февруари</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , &apos;01&apos;)">
									<span style="font-weight:bold; ">
										<xsl:text>януари</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , 07 )">
									<span style="font-weight:bold; ">
										<xsl:text>юли</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , 08 )">
									<span style="font-weight:bold; ">
										<xsl:text>август</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , 09 )">
									<span style="font-weight:bold; ">
										<xsl:text>септември</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , 10)">
									<span style="font-weight:bold; ">
										<xsl:text>октомври</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , 11 )">
									<span style="font-weight:bold; ">
										<xsl:text>ноември</xsl:text>
									</span>
								</xsl:when>
								<xsl:when test="contains(  .  , 12 )">
									<span style="font-weight:bold; ">
										<xsl:text>декември</xsl:text>
									</span>
								</xsl:when>
							</xsl:choose>
						</xsl:for-each>
						<br/>
						<xsl:for-each select="n1:YearTo">
							<span style="font-style:italic; ">
								<xsl:text>Година до: </xsl:text>
							</span>
							<span style="font-weight:bold; ">
								<xsl:apply-templates/>
							</span>
						</xsl:for-each>
					</xsl:for-each>
				</xsl:for-each>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
