<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2008 rel. 2 sp1 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:n1="http://egov.bg/RegiX/NRA/Obligations/Request" xmlns:xdt="http://www.w3.org/2005/xpath-datatypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:altova="http://www.altova.com">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.0 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:template match="/">
		<html>
			<head>
				<title/>
			</head>
			<body>
				<xsl:for-each select="$XML">
					<xsl:for-each select="n1:ObligationRequest">
						<h3 align="center">
							<span>
								<xsl:text>Входни параметри на справка за наличие/ липса на задължения</xsl:text>
							</span>
						</h3>
						<table border="0" cellpadding="0" cellspacing="0">
							<tbody>
								<tr>
									<td>
										<xsl:for-each select="n1:Identity">
											<xsl:for-each select="n1:TYPE">
												<xsl:choose>
													<xsl:when test=". =&apos;Bulstat&apos;">
														<span style="font-style:italic; ">
															<xsl:text>БУЛСТАТ</xsl:text>
														</span>
													</xsl:when>
													<xsl:when test=". =&apos;EGN&apos;">
														<span style="font-style:italic; ">
															<xsl:text>ЕГН</xsl:text>
														</span>
													</xsl:when>
													<xsl:when test=". =&apos;LNC&apos;">
														<span style="font-style:italic; ">
															<xsl:text>ЛНЧ</xsl:text>
														</span>
													</xsl:when>
													<xsl:when test=". =&apos;SystemNo&apos;">
														<span style="font-style:italic; ">
															<xsl:text>Сл. номер</xsl:text>
														</span>
													</xsl:when>
													<xsl:when test=". =&apos;BulstatCL&apos;">
														<span style="font-style:italic; ">
															<xsl:text>Чуждестранен БУЛСТАТ</xsl:text>
														</span>
													</xsl:when>
												</xsl:choose>
												<span>
													<xsl:text>: </xsl:text>
												</span>
											</xsl:for-each>
										</xsl:for-each>
									</td>
									<td>
										<xsl:for-each select="n1:Identity">
											<xsl:for-each select="n1:ID">
												<span style="font-weight:bold; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</xsl:for-each>
									</td>
								</tr>
								<tr>
									<td>
										<span style="font-style:italic; ">
											<xsl:text>Праг</xsl:text>
										</span>
									</td>
									<td>
										<xsl:for-each select="n1:Threshold">
											<span style="font-weight:bold; ">
												<xsl:apply-templates/>
											</span>
											<span>
												<xsl:text> лв.</xsl:text>
											</span>
										</xsl:for-each>
									</td>
								</tr>
							</tbody>
						</table>
					</xsl:for-each>
				</xsl:for-each>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
