//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJ_CAIS.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MJ_CAIS.Services.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достъпът Ви до https://crr-external.mjs.bg/ е активиран!.
        /// </summary>
        public static string MailBodyActivatedUser {
            get {
                return ResourceManager.GetString("MailBodyActivatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достъпът Ви до https://crr-external.mjs.bg/ е деактивиран!.
        /// </summary>
        public static string MailBodyDeactivatedUser {
            get {
                return ResourceManager.GetString("MailBodyDeactivatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достъпът Ви до https://crr-external.mjs.bg/ е отказан!.
        /// </summary>
        public static string MailBodyDeniedUser {
            get {
                return ResourceManager.GetString("MailBodyDeniedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRR-external activated user.
        /// </summary>
        public static string MailSubjectActivatedUser {
            get {
                return ResourceManager.GetString("MailSubjectActivatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRR-external deactivated user.
        /// </summary>
        public static string MailSubjectDeactivatedUser {
            get {
                return ResourceManager.GetString("MailSubjectDeactivatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRR-external denied access.
        /// </summary>
        public static string MailSubjectDeniedUser {
            get {
                return ResourceManager.GetString("MailSubjectDeniedUser", resourceCulture);
            }
        }
    }
}
