//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MJ_CAIS.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MJ_CAIS.Common.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заяви.
        /// </summary>
        public static string btnApply {
            get {
                return ResourceManager.GetString("btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказ.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преглед.
        /// </summary>
        public static string btnPreview {
            get {
                return ResourceManager.GetString("btnPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравейте,.
        /// </summary>
        public static string lblGreetingUser {
            get {
                return ResourceManager.GetString("lblGreetingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изход.
        /// </summary>
        public static string lblLogout {
            get {
                return ResourceManager.GetString("lblLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моля, свържете се с администратор..
        /// </summary>
        public static string MsgContactYourAdministrator {
            get {
                return ResourceManager.GetString("MsgContactYourAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна грешка при извършване на операцията в базата от данни..
        /// </summary>
        public static string MsgDataBaseError {
            get {
                return ResourceManager.GetString("MsgDataBaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма намерени данни.
        /// </summary>
        public static string MsgDataNotFound {
            get {
                return ResourceManager.GetString("MsgDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записът беше успешно изтрит..
        /// </summary>
        public static string MsgDeleteSuccessfull {
            get {
                return ResourceManager.GetString("MsgDeleteSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидна електронна поща.
        /// </summary>
        public static string MsgEmailInvalid {
            get {
                return ResourceManager.GetString("MsgEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страницата, която се опитвате да достъпите, не е намерена. (HTTP Status Code: 404).
        /// </summary>
        public static string MsgError404 {
            get {
                return ResourceManager.GetString("MsgError404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна системна грешка. .
        /// </summary>
        public static string MsgErrorOccurred {
            get {
                return ResourceManager.GetString("MsgErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидно потребителско име или парола.
        /// </summary>
        public static string MsgInvalidloginAttempt {
            get {
                return ResourceManager.GetString("MsgInvalidloginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;{0}&quot; трябва да е максимум {1} символа..
        /// </summary>
        public static string MsgMinLength {
            get {
                return ResourceManager.GetString("MsgMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тази транзакция не се поддържа..
        /// </summary>
        public static string MsgNotSuportedTransaction {
            get {
                return ResourceManager.GetString("MsgNotSuportedTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна грешка при извършване на операцията..
        /// </summary>
        public static string MsgOperationException {
            get {
                return ResourceManager.GetString("MsgOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полето &quot;{0}&quot; е задължително.
        /// </summary>
        public static string MsgRequired {
            get {
                return ResourceManager.GetString("MsgRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възникна грешка при изпълняване на операцията!.
        /// </summary>
        public static string MsgSaveError {
            get {
                return ResourceManager.GetString("MsgSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данните бяха записани успешно..
        /// </summary>
        public static string MsgSaveSuccessfull {
            get {
                return ResourceManager.GetString("MsgSaveSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сесията Ви е изтекла..
        /// </summary>
        public static string MsgSessionExpired {
            get {
                return ResourceManager.GetString("MsgSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителят е заключен.
        /// </summary>
        public static string MsgUserLockout {
            get {
                return ResourceManager.GetString("MsgUserLockout", resourceCulture);
            }
        }
    }
}
