<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2008 rel. 2 sp1 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:common="http://egov.bg/RegiX/GRAO/NBD" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:n1="http://egov.bg/RegiX/GRAO/NBD/RelationsResponse" xmlns:xdt="http://www.w3.org/2005/xpath-datatypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:altova="http://www.altova.com">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.0 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:decimal-format name="format1" grouping-separator=" " decimal-separator=","/>
	<xsl:import-schema schema-location="D:\Projects\eGov\RegiX\RegiX.GraoNBDAdapter\XMLSchemas\RelationsResponse.xsd" namespace="http://egov.bg/RegiX/GRAO/NBD/RelationsResponse"/>
	<xsl:template match="/">
		<html>
			<head>
				<title/>
			</head>
			<body>
				<xsl:for-each select="$XML">
					<xsl:for-each select="n1:RelationsResponse">
						<h3 align="center">
							<span>
								<xsl:text>Министерство на регионалното развитие и благоустройството</xsl:text>
							</span>
							<br/>
							<span>
								<xsl:text>Класификатор на настоящите и постоянните адреси</xsl:text>
							</span>
						</h3>
						<h2 align="center">
							<span>
								<xsl:text>Справка за родственост</xsl:text>
							</span>
						</h2>
						<xsl:choose>
							<xsl:when test="string-length( . ) &gt; 0">
								<table style="border-collapse:collapse; " border="1" width="100%">
									<thead>
										<tr>
											<th style="padding:4px; " align="left">
												<span>
													<xsl:text>Име: </xsl:text>
												</span>
												<span style="font-weight:normal; ">
													<xsl:text>собствено, бащино, фамилно</xsl:text>
												</span>
											</th>
											<th height="29">
												<span>
													<xsl:text>ЕГН</xsl:text>
												</span>
											</th>
											<th height="29">
												<span>
													<xsl:text>Дата на раждане</xsl:text>
												</span>
											</th>
											<th height="29">
												<span>
													<xsl:text>Вид родственост</xsl:text>
												</span>
											</th>
											<th height="29">
												<span>
													<xsl:text>Пол</xsl:text>
												</span>
											</th>
											<th height="29">
												<span>
													<xsl:text>Националност</xsl:text>
												</span>
											</th>
											<th height="29">
												<span>
													<xsl:text>Дата на смърт</xsl:text>
												</span>
											</th>
										</tr>
									</thead>
									<tbody>
										<xsl:for-each select="n1:PersonRelations">
											<tr>
												<td style="padding:4px; ">
													<xsl:for-each select="common:FirstName">
														<xsl:apply-templates/>
													</xsl:for-each>
													<xsl:for-each select="common:SurName">
														<span>
															<xsl:text>&#160;</xsl:text>
														</span>
														<xsl:apply-templates/>
													</xsl:for-each>
													<xsl:for-each select="common:FamilyName">
														<span>
															<xsl:text>&#160;</xsl:text>
														</span>
														<xsl:apply-templates/>
													</xsl:for-each>
												</td>
												<td align="center">
													<xsl:for-each select="common:EGN">
														<xsl:apply-templates/>
													</xsl:for-each>
												</td>
												<td align="center">
													<xsl:for-each select="common:BirthDate">
														<span>
															<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
															<xsl:text>.</xsl:text>
															<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
															<xsl:text>.</xsl:text>
															<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
														</span>
														<span>
															<xsl:text> г.</xsl:text>
														</span>
													</xsl:for-each>
												</td>
												<td align="center">
													<xsl:for-each select="common:RelationCode">
														<xsl:apply-templates/>
													</xsl:for-each>
												</td>
												<td align="center">
													<xsl:for-each select="common:Gender">
														<xsl:for-each select="common:GenderName">
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:for-each>
												</td>
												<td align="center">
													<xsl:for-each select="common:Nationality">
														<xsl:for-each select="common:NationalityName">
															<xsl:apply-templates/>
														</xsl:for-each>
														<xsl:for-each select="common:NationalityName2">
															<span>
																<xsl:text> / </xsl:text>
															</span>
															<xsl:apply-templates/>
														</xsl:for-each>
													</xsl:for-each>
												</td>
												<td align="center">
													<xsl:for-each select="common:DeathDate">
														<span>
															<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
															<xsl:text>.</xsl:text>
															<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
															<xsl:text>.</xsl:text>
															<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
														</span>
														<span>
															<xsl:text> г.</xsl:text>
														</span>
													</xsl:for-each>
												</td>
											</tr>
										</xsl:for-each>
									</tbody>
								</table>
							</xsl:when>
							<xsl:otherwise>
								<span>
									<xsl:text>В регистъра не са намерени данни за подаденото ЕГН.</xsl:text>
								</span>
							</xsl:otherwise>
						</xsl:choose>
						<br/>
					</xsl:for-each>
				</xsl:for-each>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
