using AutoMapper;
using MJ_CAIS.AutoMapperContainer.Resolvers;
using MJ_CAIS.Common.Constants;
using MJ_CAIS.Common.Enums;
using MJ_CAIS.DataAccess.Entities;
using MJ_CAIS.DTO.ExternalServicesHost;

namespace MJ_CAIS.AutoMapperContainer.MappingProfiles
{
    public class CriminalRecordsReportProfile : Profile
    {
        public CriminalRecordsReportProfile()
        {
            CreateMap<BBulletin, BulletinType>()
               .ForMember(d => d.Type, opt => opt.MapFrom(src => src.BulletinType == nameof(BulletinConstants.Type.Bulletin78A) ? BulletinTypesType.Bulletin78A :
                    src.BulletinType == nameof(BulletinConstants.Type.ConvictionBulletin) ? BulletinTypesType.ConvictionBulletin : BulletinTypesType.Unspecified))
               .ForPath(d => d.Person.NamesBg.FirstName, opt => opt.MapFrom(src => src.Firstname))
               .ForPath(d => d.Person.NamesBg.SurName, opt => opt.MapFrom(src => src.Surname))
               .ForPath(d => d.Person.NamesBg.FamilyName, opt => opt.MapFrom(src => src.Familyname))
               .ForPath(d => d.Person.NamesBg.FullName, opt => opt.MapFrom(src => src.Fullname))
               .ForPath(d => d.Person.NamesEn.FirstName, opt => opt.MapFrom(src => src.FirstnameLat))
               .ForPath(d => d.Person.NamesEn.SurName, opt => opt.MapFrom(src => src.Surname))
               .ForPath(d => d.Person.NamesEn.FamilyName, opt => opt.MapFrom(src => src.FamilynameLat))
               .ForPath(d => d.Person.NamesEn.FullName, opt => opt.MapFrom(src => src.FullnameLat))
               .ForPath(d => d.Person.Sex, opt => opt.MapFrom(src => src.Sex))
               .ForPath(d => d.Person.IdentityNumber.EGN, opt => opt.MapFrom(src => src.Egn))
               .ForPath(d => d.Person.IdentityNumber.LNCh, opt => opt.MapFrom(src => src.Lnch))
               .ForPath(d => d.Person.IdentityNumber.LN, opt => opt.MapFrom(src => src.Ln))
               .ForPath(d => d.Person.IdentityNumber.SUID, opt => opt.MapFrom(src => src.Suid))
               .ForPath(d => d.Person.BirthDate, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDateType(src.BirthDate, src.BirthDatePrecision)))
               .ForPath(d => d.Person.BirthPlace.Country, opt => opt.MapFrom(src => src.BirthCountry))
               .ForPath(d => d.Person.BirthPlace.City, opt => opt.MapFrom(src => src.BirthCity))
               .ForPath(d => d.Person.BirthPlace.Descr, opt => opt.MapFrom(src => src.BirthPlaceOther))
               .ForPath(d => d.Person.PersonNationality, opt => opt.MapFrom(src => src.BPersNationalities))
               .ForPath(d => d.Person.PersonIdentificationDocument.IdentificationDocumentCategoryReference, opt => opt.MapFrom(src => CriminalRecordsReportResolver.StringToEnum<IdentificationDocumentCategoryType>(src.IdDocCategoryId)))
               .ForPath(d => d.Person.PersonIdentificationDocument.IdentificationDocumentType1, opt => opt.MapFrom(src => src.IdDocTypeDescr))
               .ForPath(d => d.Person.PersonIdentificationDocument.IdentificationDocumentNumber, opt => opt.MapFrom(src => src.IdDocNumber))
               .ForPath(d => d.Person.PersonIdentificationDocument.IdentificationDocumentIssuingAuthority, opt => opt.MapFrom(src => src.IdDocIssuingAuthority))
               .ForPath(d => d.Person.PersonIdentificationDocument.IdentificationDocumentIssuingDate, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDateType(src.IdDocIssuingDate, src.IdDocIssuingDatePrec)))
               .ForPath(d => d.Person.PersonIdentificationDocument.IdentificationDocumentValidUntil, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDateType(src.IdDocValidDate, src.IdDocValidDatePrec)))
               .ForPath(d => d.Person.MotherNames.FirstName, opt => opt.MapFrom(src => src.MotherFirstname))
               .ForPath(d => d.Person.MotherNames.SurName, opt => opt.MapFrom(src => src.MotherSurname))
               .ForPath(d => d.Person.MotherNames.FamilyName, opt => opt.MapFrom(src => src.MotherFamilyname))
               .ForPath(d => d.Person.MotherNames.FullName, opt => opt.MapFrom(src => src.MotherFullname))
               .ForPath(d => d.Person.FatherNames.FirstName, opt => opt.MapFrom(src => src.FatherFirstname))
               .ForPath(d => d.Person.FatherNames.SurName, opt => opt.MapFrom(src => src.FatherSurname))
               .ForPath(d => d.Person.FatherNames.FamilyName, opt => opt.MapFrom(src => src.FatherFamilyname))
               .ForPath(d => d.Person.FatherNames.FullName, opt => opt.MapFrom(src => src.FatherFullname))
               .ForPath(d => d.Person.AFISNumber, opt => opt.MapFrom(src => src.AfisNumber))
               .ForPath(d => d.Conviction.Decision.FileNumber, opt => opt.MapFrom(src => src.DecisionNumber))
               .ForPath(d => d.Conviction.Decision.DecisionDate, opt => opt.MapFrom(src => src.DecisionDate))
               .ForPath(d => d.Conviction.Decision.DecisionFinalDate, opt => opt.MapFrom(src => src.DecisionFinalDate))
               .ForPath(d => d.Conviction.Decision.DecidingAuthority, opt => opt.MapFrom(src => src.DecidingAuth))
               .ForPath(d => d.Conviction.Decision.ECLI, opt => opt.MapFrom(src => src.DecisionEcli))
               .ForPath(d => d.Conviction.Decision.DecisionType, opt => opt.MapFrom(src => src.DecisionType.Name))
               .ForPath(d => d.Conviction.CriminalCase.CaseType, opt => opt.MapFrom(src => src.CaseType.Name))
               .ForPath(d => d.Conviction.CriminalCase.CaseNumber, opt => opt.MapFrom(src => src.CaseNumber))
               .ForPath(d => d.Conviction.CriminalCase.CaseYear, opt => opt.MapFrom(src => src.CaseTypeId))
               .ForPath(d => d.Conviction.CriminalCase.CaseAuthority, opt => opt.MapFrom(src => src.CaseAuth))
               .ForPath(d => d.Conviction.ConvictionRemarks, opt => opt.MapFrom(src => src.ConvRemarks))
               .ForPath(d => d.Conviction.ConvictionOffence, opt => opt.MapFrom(src => src.BOffences))
               .ForPath(d => d.Conviction.WithoutSanction, opt => opt.MapFrom(src => src.NoSanction))
               .ForPath(d => d.Conviction.WithoutSanctionSpecified, opt => opt.MapFrom(src => src.NoSanction.HasValue))
               .ForPath(d => d.Conviction.ConvictionSanction, opt => opt.MapFrom(src => src.BSanctions))
               .ForPath(d => d.Conviction.ServingPrevSuspendedSentence, opt => opt.MapFrom(src => src.PrevSuspSent))
               .ForPath(d => d.Conviction.ServingPrevSuspendedSentenceSpecified, opt => opt.MapFrom(src => src.PrevSuspSent.HasValue))
               .ForPath(d => d.Conviction.ServingPrevSuspendedSentenceActNumber, opt => opt.MapFrom(src => src.PrevSuspSentDescr))
               .ForPath(d => d.Conviction.ConvictionDecisions, opt => opt.MapFrom(src => src.BDecisions))
               .ForPath(d => d.Conviction.EcrisConvictionId, opt => opt.MapFrom(src => src.EcrisConvictionId))
               .ForPath(d => d.IssuerData.BulletinCreateDate, opt => opt.MapFrom(src => src.CreatedOn))
               .ForPath(d => d.IssuerData.BulletinCreatorPerson.Names.FullName, opt => opt.MapFrom(src => src.CreatedByNames))
               .ForPath(d => d.IssuerData.BulletinCreatorPerson.Position, opt => opt.MapFrom(src => src.CreatedByPosition))
               .ForPath(d => d.IssuerData.BulletinApproverPerson.Names.FullName, opt => opt.MapFrom(src => src.ApprovedByNames))
               .ForPath(d => d.IssuerData.BulletinApproverPerson.Position, opt => opt.MapFrom(src => src.ApprovedByPosition))
               .ForPath(d => d.IssuerData.BulletinCreatorAuthority, opt => opt.MapFrom(src => src.BulletinAuthority))
               .ForPath(d => d.RegistrationData.RegistrationNumber, opt => opt.MapFrom(src => src.RegistrationNumber))
               .ForPath(d => d.RegistrationData.BulletinAlphabeticalIndex, opt => opt.MapFrom(src => src.AlphabeticalIndex))
               .ForPath(d => d.RegistrationData.BulletinReceivedDate, opt => opt.MapFrom(src => src.BulletinReceivedDate))
               .ForPath(d => d.RegistrationData.BulletinReceivedDateSpecified, opt => opt.MapFrom(src => src.BulletinReceivedDate.HasValue))
               .ForPath(d => d.RegistrationData.ConvictionStatusAuthority.Name, opt => opt.MapFrom(src => src.CsAuthority.Name))
               .ForPath(d => d.RegistrationData.ConvictionStatusAuthority.Code, opt => opt.MapFrom(src => src.CsAuthority.Code))
               .ReverseMap()
               .ForMember(d => d.BulletinType, opt => opt.MapFrom(src => src.Type.ToString()))
               .ForMember(d => d.Firstname, opt => opt.MapFrom(src => src.Person.NamesBg.FirstName))
               .ForMember(d => d.Surname, opt => opt.MapFrom(src => src.Person.NamesBg.SurName))
               .ForMember(d => d.Familyname, opt => opt.MapFrom(src => src.Person.NamesBg.FamilyName))
               .ForMember(d => d.Fullname, opt => opt.MapFrom(src => src.Person.NamesBg.FullName))
               .ForMember(d => d.FirstnameLat, opt => opt.MapFrom(src => src.Person.NamesEn.FirstName))
               .ForMember(d => d.Surname, opt => opt.MapFrom(src => src.Person.NamesEn.SurName))
               .ForMember(d => d.FamilynameLat, opt => opt.MapFrom(src => src.Person.NamesEn.FamilyName))
               .ForMember(d => d.FullnameLat, opt => opt.MapFrom(src => src.Person.NamesEn.FullName))
               .ForMember(d => d.Sex, opt => opt.MapFrom(src => src.Person.Sex))
               .ForMember(d => d.Egn, opt => opt.MapFrom(src => src.Person.IdentityNumber.EGN))
               .ForMember(d => d.Lnch, opt => opt.MapFrom(src => src.Person.IdentityNumber.LNCh))
               .ForMember(d => d.Ln, opt => opt.MapFrom(src => src.Person.IdentityNumber.LN))
               .ForMember(d => d.Suid, opt => opt.MapFrom(src => src.Person.IdentityNumber.SUID))
               .ForMember(d => d.BirthDate, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDateTimeFromDateType(src.Person.BirthDate)))
               .ForMember(d => d.BirthDatePrecision, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDatePrecFromDateType(src.Person.BirthDate)))
               .ForMember(d => d.BirthCountry, opt => opt.MapFrom(src => src.Person.BirthPlace.Country))
               .ForMember(d => d.BirthCity, opt => opt.MapFrom(src => src.Person.BirthPlace.City))
               .ForMember(d => d.BirthPlaceOther, opt => opt.MapFrom(src => src.Person.BirthPlace.Descr))
               .ForMember(d => d.BPersNationalities, opt => opt.MapFrom(src => src.Person.PersonNationality))
               .ForMember(d => d.IdDocCategoryId, opt => opt.MapFrom(src => CriminalRecordsReportResolver.EnumToString(src.Person.PersonIdentificationDocument.IdentificationDocumentCategoryReference)))
               .ForMember(d => d.IdDocTypeDescr, opt => opt.MapFrom(src => src.Person.PersonIdentificationDocument.IdentificationDocumentType1))
               .ForMember(d => d.IdDocNumber, opt => opt.MapFrom(src => src.Person.PersonIdentificationDocument.IdentificationDocumentNumber))
               .ForMember(d => d.IdDocIssuingAuthority, opt => opt.MapFrom(src => src.Person.PersonIdentificationDocument.IdentificationDocumentIssuingAuthority))
               .ForMember(d => d.IdDocIssuingDate, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDateTimeFromDateType(src.Person.PersonIdentificationDocument.IdentificationDocumentIssuingDate)))
               .ForMember(d => d.IdDocIssuingDatePrec, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDatePrecFromDateType(src.Person.PersonIdentificationDocument.IdentificationDocumentIssuingDate)))
               .ForMember(d => d.IdDocValidDate, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDateTimeFromDateType(src.Person.PersonIdentificationDocument.IdentificationDocumentValidUntil)))
               .ForMember(d => d.IdDocValidDatePrec, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDatePrecFromDateType(src.Person.PersonIdentificationDocument.IdentificationDocumentValidUntil)))
               .ForMember(d => d.MotherFirstname, opt => opt.MapFrom(src => src.Person.MotherNames.FirstName))
               .ForMember(d => d.MotherSurname, opt => opt.MapFrom(src => src.Person.MotherNames.SurName))
               .ForMember(d => d.MotherFamilyname, opt => opt.MapFrom(src => src.Person.MotherNames.FamilyName))
               .ForMember(d => d.MotherFullname, opt => opt.MapFrom(src => src.Person.MotherNames.FullName))
               .ForMember(d => d.FatherFirstname, opt => opt.MapFrom(src => src.Person.FatherNames.FirstName))
               .ForMember(d => d.FatherSurname, opt => opt.MapFrom(src => src.Person.FatherNames.SurName))
               .ForMember(d => d.FatherFamilyname, opt => opt.MapFrom(src => src.Person.FatherNames.FamilyName))
               .ForMember(d => d.FatherFullname, opt => opt.MapFrom(src => src.Person.FatherNames.FullName))
               .ForMember(d => d.AfisNumber, opt => opt.MapFrom(src => src.Person.AFISNumber))
               .ForMember(d => d.DecisionNumber, opt => opt.MapFrom(src => src.Conviction.Decision.FileNumber))
               .ForMember(d => d.DecisionDate, opt => opt.MapFrom(src => src.Conviction.Decision.DecisionDate))
               .ForMember(d => d.DecisionFinalDate, opt => opt.MapFrom(src => src.Conviction.Decision.DecisionFinalDate))
               .ForMember(d => d.DecidingAuth, opt => opt.MapFrom(src => src.Conviction.Decision.DecidingAuthority))
               .ForMember(d => d.DecisionEcli, opt => opt.MapFrom(src => src.Conviction.Decision.ECLI))
               .ForPath(d => d.DecisionType.Name, opt => opt.MapFrom(src => src.Conviction.Decision.DecisionType))
               .ForPath(d => d.CaseType.Name, opt => opt.MapFrom(src => src.Conviction.CriminalCase.CaseType))
               .ForMember(d => d.CaseNumber, opt => opt.MapFrom(src => src.Conviction.CriminalCase.CaseNumber))
               .ForMember(d => d.CaseTypeId, opt => opt.MapFrom(src => src.Conviction.CriminalCase.CaseYear))
               .ForMember(d => d.CaseAuth, opt => opt.MapFrom(src => src.Conviction.CriminalCase.CaseAuthority))
               .ForMember(d => d.ConvRemarks, opt => opt.MapFrom(src => src.Conviction.ConvictionRemarks))
               .ForMember(d => d.BOffences, opt => opt.MapFrom(src => src.Conviction.ConvictionOffence))
               .ForMember(d => d.NoSanction, opt => opt.MapFrom(src => src.Conviction.WithoutSanction))
               .ForMember(d => d.BSanctions, opt => opt.MapFrom(src => src.Conviction.ConvictionSanction))
               .ForMember(d => d.PrevSuspSent, opt => opt.MapFrom(src => src.Conviction.ServingPrevSuspendedSentence))
               .ForMember(d => d.PrevSuspSentDescr, opt => opt.MapFrom(src => src.Conviction.ServingPrevSuspendedSentenceActNumber))
               .ForMember(d => d.BDecisions, opt => opt.MapFrom(src => src.Conviction.ConvictionDecisions))
               .ForMember(d => d.EcrisConvictionId, opt => opt.MapFrom(src => src.Conviction.EcrisConvictionId))
               .ForMember(d => d.CreatedOn, opt => opt.MapFrom(src => src.IssuerData.BulletinCreateDate))
               .ForMember(d => d.CreatedByNames, opt => opt.MapFrom(src => src.IssuerData.BulletinCreatorPerson.Names.FullName))
               .ForMember(d => d.CreatedByPosition, opt => opt.MapFrom(src => src.IssuerData.BulletinCreatorPerson.Position))
               .ForMember(d => d.ApprovedByNames, opt => opt.MapFrom(src => src.IssuerData.BulletinApproverPerson.Names.FullName))
               .ForMember(d => d.ApprovedByPosition, opt => opt.MapFrom(src => src.IssuerData.BulletinApproverPerson.Position))
               .ForMember(d => d.BulletinAuthority, opt => opt.MapFrom(src => src.IssuerData.BulletinCreatorAuthority))
               .ForMember(d => d.RegistrationNumber, opt => opt.MapFrom(src => src.RegistrationData.RegistrationNumber))
               .ForMember(d => d.AlphabeticalIndex, opt => opt.MapFrom(src => src.RegistrationData.BulletinAlphabeticalIndex))
               .ForMember(d => d.BulletinReceivedDate, opt => opt.MapFrom(src => src.RegistrationData.BulletinReceivedDate))
               .ForPath(d => d.CsAuthority.Name, opt => opt.MapFrom(src => src.RegistrationData.ConvictionStatusAuthority.Name))
               .ForPath(d => d.CsAuthority.Code, opt => opt.MapFrom(src => src.RegistrationData.ConvictionStatusAuthority.Code));

            CreateMap<GCountry, CountryType>()
                .ForMember(d => d.CountryISONumber, opt => opt.MapFrom(src => src.Iso31662Number))
                .ForMember(d => d.CountryISOAlpha3, opt => opt.MapFrom(src => src.Iso3166Alpha2))
                .ForMember(d => d.CountryName, opt => opt.MapFrom(src => src.Name))
                .ReverseMap();

            CreateMap<GCity, CityType>()
               .ForMember(d => d.EKATTECode, opt => opt.MapFrom(src => src.EkatteCode))
               .ForMember(d => d.CityName, opt => opt.MapFrom(src => src.Name))
               .ReverseMap();

            CreateMap<BPersNationality, CountryType>()
                .ForMember(d => d.CountryISOAlpha3, opt => opt.MapFrom(src => src.Country.Iso3166Alpha2))
                .ForMember(d => d.CountryName, opt => opt.MapFrom(src => src.Country.Name))
                .ForMember(d => d.CountryISONumber, opt => opt.MapFrom(src => src.Country.Iso31662Number))
                .ReverseMap()
                .ForPath(d => d.Country.Iso3166Alpha2, opt => opt.MapFrom(src => src.CountryISOAlpha3))
                .ForPath(d => d.Country.Name, opt => opt.MapFrom(src => src.CountryName))
                .ForPath(d => d.Country.Iso31662Number, opt => opt.MapFrom(src => src.CountryISONumber))
                .ForMember(d => d.EntityState, opt => opt.MapFrom(src => EntityStateEnum.Added));

            CreateMap<GDecidingAuthority, DecidingAuthorityType>()
                .ForMember(d => d.DecidingAuthorityName, opt => opt.MapFrom(src => src.Name))
                .ForMember(d => d.DecidingAuthorityCodeEIK, opt => opt.MapFrom(src => src.Code))
                .ForMember(d => d.DecidingAuthorityCodeEISPP, opt => opt.MapFrom(src => src.EisppCode))
                .ReverseMap();

            CreateMap<BOffence, OffenceType>()
               //.ForMember(d => d.OffenceId, opt => opt.MapFrom(src => src.OffenceId)) // todo 
               .ForMember(d => d.NationalCategoryCode, opt => opt.MapFrom(src => src.OffenceCat.Code))
               .ForMember(d => d.NationalCategoryTitle, opt => opt.MapFrom(src => src.OffenceCat.Name))
               .ForMember(d => d.Remarks, opt => opt.MapFrom(src => src.Remarks))
               .ForPath(d => d.OffenceCommonCategoryReference.OffenceCode, opt => opt.MapFrom(src => src.EcrisOffCat.Id))
               .ForPath(d => d.OffenceCommonCategoryReference.OffenceName, opt => opt.MapFrom(src => src.EcrisOffCat.Name))
               .ForMember(d => d.OffenceApplicableLegalProvisions, opt => opt.MapFrom(src => src.LegalProvisions))
               .ForMember(d => d.OffenceStartDate, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDateType(src.OffStartDate, src.OffStartDatePrec)))
               .ForMember(d => d.OffenceEndDate, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDateType(src.OffEndDate, src.OffEndDatePrec)))
               .ForPath(d => d.OffencePlace.Country, opt => opt.MapFrom(src => src.OffPlaceCountry))
               .ForPath(d => d.OffencePlace.City, opt => opt.MapFrom(src => src.OffPlaceCity))
               .ForPath(d => d.OffencePlace.Descr, opt => opt.MapFrom(src => src.OffPlaceDescr))
               .ForMember(d => d.FormOfGuilt, opt => opt.MapFrom(src => src.FormOfGuiltId))
               .ForMember(d => d.FormOfGuiltSpecified, opt => opt.MapFrom(src => string.IsNullOrEmpty(src.FormOfGuiltId)))
               .ReverseMap()
               .ForPath(d => d.OffenceCat.Code, opt => opt.MapFrom(src => src.NationalCategoryCode))
               .ForPath(d => d.OffenceCat.Name, opt => opt.MapFrom(src => src.NationalCategoryTitle))
               .ForPath(d => d.EcrisOffCat.Id, opt => opt.MapFrom(src => src.OffenceCommonCategoryReference.OffenceCode))
               .ForPath(d => d.EcrisOffCat.Name, opt => opt.MapFrom(src => src.OffenceCommonCategoryReference.OffenceName))
               .ForMember(d => d.LegalProvisions, opt => opt.MapFrom(src => src.OffenceApplicableLegalProvisions))
               .ForMember(d => d.OffStartDate, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDateTimeFromDateType(src.OffenceStartDate)))
               .ForMember(d => d.OffStartDatePrec, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDatePrecFromDateType(src.OffenceStartDate)))
               .ForMember(d => d.OffEndDate, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDateTimeFromDateType(src.OffenceEndDate)))
               .ForMember(d => d.OffEndDatePrec, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDatePrecFromDateType(src.OffenceEndDate)))
               .ForMember(d => d.OffPlaceCountry, opt => opt.MapFrom(src => src.OffencePlace.Country))
               .ForPath(d => d.OffPlaceCity, opt => opt.MapFrom(src => src.OffencePlace.City))
               .ForPath(d => d.OffPlaceDescr, opt => opt.MapFrom(src => src.OffencePlace.Descr))
               .ForMember(d => d.FormOfGuiltId, opt => opt.MapFrom(src => src.FormOfGuilt.ToString()))
               .ForMember(d => d.EntityState, opt => opt.MapFrom(src => EntityStateEnum.Added));

            CreateMap<BSanction, SanctionType>()
              //.ForMember(d => d.SanctionId, opt => opt.MapFrom(src => src.SanctionId)) // todo
              .ForMember(d => d.NationalCategoryCode, opt => opt.MapFrom(src => src.SanctCategory.Code))
              .ForMember(d => d.NationalCategoryTitle, opt => opt.MapFrom(src => src.SanctCategory.Name))
              .ForPath(d => d.SanctionCommonCategoryReference.SanctionCode, opt => opt.MapFrom(src => src.EcrisSanctCateg.Category))
              .ForPath(d => d.SanctionCommonCategoryReference.SanctionText, opt => opt.MapFrom(src => src.EcrisSanctCateg.Name))
              .ForPath(d => d.Fine.SanctionAmountOfIndividualFine, opt => opt.MapFrom(src => src.FineAmount))
              .ForPath(d => d.Fine.SanctionAmountOfIndividualFineSpecified, opt => opt.MapFrom(src => src.FineAmount.HasValue))
              .ForMember(d => d.Probation, opt => opt.MapFrom(src => src.BProbations))
              .ForPath(d => d.Prison.SanctionSentencedPeriod, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetPeriodFromNumbers(src.DecisionDurationYears, src.DecisionDurationMonths, src.DecisionDurationDays, src.DecisionDurationHours)))
              .ForPath(d => d.Prison.SanctionSuspension, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetPeriodFromNumbers(src.SuspentionDurationYears, src.SuspentionDurationMonths, src.SuspentionDurationDays, src.SuspentionDurationHours)))
              .ForPath(d => d.Prison.DetentionDescription, opt => opt.MapFrom(src => src.DetenctionDescr))
              .ForPath(d => d.Other.SanctionSentencedPeriodLength, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetPeriodFromNumbers(src.DecisionDurationYears, src.DecisionDurationMonths, src.DecisionDurationDays, src.DecisionDurationHours)))
              .ReverseMap()
              .ForPath(d => d.SanctCategory.Code, opt => opt.MapFrom(src => src.NationalCategoryCode))
              .ForPath(d => d.SanctCategory.Name, opt => opt.MapFrom(src => src.NationalCategoryTitle))
              .ForPath(d => d.EcrisSanctCateg.Category, opt => opt.MapFrom(src => src.SanctionCommonCategoryReference.SanctionCode))
              .ForPath(d => d.EcrisSanctCateg.Name, opt => opt.MapFrom(src => src.SanctionCommonCategoryReference.SanctionText))
              .ForPath(d => d.FineAmount, opt => opt.MapFrom(src => src.Fine.SanctionAmountOfIndividualFine))
              .ForMember(d => d.BProbations, opt => opt.MapFrom(src => src.Probation))
              .ForMember(d => d.DecisionDurationYears, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDurationPart(src.Prison.SanctionSentencedPeriod, CriminalRecordsReportResolver.DurationYearPattern)))
              .ForMember(d => d.DecisionDurationMonths, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDurationPart(src.Prison.SanctionSentencedPeriod, CriminalRecordsReportResolver.DurationMonthPattern)))
              .ForMember(d => d.DecisionDurationDays, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDurationPart(src.Prison.SanctionSentencedPeriod, CriminalRecordsReportResolver.DurationDayPattern)))
              .ForMember(d => d.DecisionDurationHours, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDurationPart(src.Prison.SanctionSentencedPeriod, CriminalRecordsReportResolver.DurationHourPattern)))
              .ForMember(d => d.SuspentionDurationYears, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDurationPart(src.Prison.SanctionSuspension, CriminalRecordsReportResolver.DurationYearPattern)))
              .ForMember(d => d.SuspentionDurationMonths, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDurationPart(src.Prison.SanctionSuspension, CriminalRecordsReportResolver.DurationMonthPattern)))
              .ForMember(d => d.SuspentionDurationDays, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDurationPart(src.Prison.SanctionSuspension, CriminalRecordsReportResolver.DurationDayPattern)))
              .ForMember(d => d.SuspentionDurationHours, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDurationPart(src.Prison.SanctionSuspension, CriminalRecordsReportResolver.DurationHourPattern)))
              .ForMember(d => d.DetenctionDescr, opt => opt.MapFrom(src => src.Prison.DetentionDescription))
              .ForMember(d => d.DecisionDurationYears, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDurationPart(src.Other.SanctionSentencedPeriodLength, CriminalRecordsReportResolver.DurationYearPattern)))
              .ForMember(d => d.DecisionDurationMonths, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDurationPart(src.Other.SanctionSentencedPeriodLength, CriminalRecordsReportResolver.DurationMonthPattern)))
              .ForMember(d => d.DecisionDurationDays, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDurationPart(src.Other.SanctionSentencedPeriodLength, CriminalRecordsReportResolver.DurationDayPattern)))
              .ForMember(d => d.DecisionDurationHours, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDurationPart(src.Other.SanctionSentencedPeriodLength, CriminalRecordsReportResolver.DurationHourPattern)))
              .ForMember(d => d.EntityState, opt => opt.MapFrom(src => EntityStateEnum.Added));

            CreateMap<BProbation, SanctionTypeProbation>()
                //.ForMember(d => d.SanctionId, opt => opt.MapFrom(src => src.SanctionId)) // todo
                .ForMember(d => d.ProbationCategoryCode, opt => opt.MapFrom(src => src.SanctProbCateg.Code))
                .ForMember(d => d.ProbationCategoryTitle, opt => opt.MapFrom(src => src.SanctProbCateg.Name))
                .ForMember(d => d.ProbationValue, opt => opt.MapFrom(src => src.SanctProbValue))
                .ForMember(d => d.ProbationValueSpecified, opt => opt.MapFrom(src => src.SanctProbValue.HasValue))
                .ForMember(d => d.ProbationMeasureCode, opt => opt.MapFrom(src => src.SanctProbMeasure.Code))
                .ForMember(d => d.ProbationMeasureTitle, opt => opt.MapFrom(src => src.SanctProbMeasure.Name))
                .ForMember(d => d.SanctionSentencedPeriod, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetPeriodFromNumbers(src.DecisionDurationYears, src.DecisionDurationMonths, src.DecisionDurationDays, src.DecisionDurationHours)))
                .ReverseMap()
                .ForPath(d => d.SanctProbCateg.Code, opt => opt.MapFrom(src => src.ProbationCategoryCode))
                .ForPath(d => d.SanctProbCateg.Name, opt => opt.MapFrom(src => src.ProbationCategoryTitle))
                .ForPath(d => d.SanctProbValue, opt => opt.MapFrom(src => src.ProbationValue))
                .ForPath(d => d.SanctProbMeasure.Code, opt => opt.MapFrom(src => src.ProbationMeasureCode))
                .ForPath(d => d.SanctProbMeasure.Name, opt => opt.MapFrom(src => src.ProbationMeasureTitle))
                .ForMember(d => d.DecisionDurationYears, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDurationPart(src.SanctionSentencedPeriod, CriminalRecordsReportResolver.DurationYearPattern)))
                .ForMember(d => d.DecisionDurationMonths, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDurationPart(src.SanctionSentencedPeriod, CriminalRecordsReportResolver.DurationMonthPattern)))
                .ForMember(d => d.DecisionDurationDays, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDurationPart(src.SanctionSentencedPeriod, CriminalRecordsReportResolver.DurationDayPattern)))
                .ForMember(d => d.DecisionDurationHours, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDurationPart(src.SanctionSentencedPeriod, CriminalRecordsReportResolver.DurationHourPattern)))
                .ForMember(d => d.EntityState, opt => opt.MapFrom(src => EntityStateEnum.Added));

            CreateMap<BDecision, DecisionChangeType>()
                .ForMember(d => d.DecisionChangeTypeReference, opt => opt.MapFrom(src => CriminalRecordsReportResolver.StringToEnum<DecisionChangeTypeType>(src.DecisionChTypeId)))
                .ForMember(d => d.DecisionChangeTypeReferenceSpecified, opt => opt.MapFrom(src => !string.IsNullOrEmpty(src.DecisionChTypeId)))
                .ForPath(d => d.Decision.FileNumber, opt => opt.MapFrom(src => src.DecisionNumber))
                .ForPath(d => d.Decision.DecisionFinalDate, opt => opt.MapFrom(src => src.DecisionFinalDate))
                .ForPath(d => d.Decision.DecisionDate, opt => opt.MapFrom(src => src.DecisionDate))
                .ForPath(d => d.Decision.DecidingAuthority, opt => opt.MapFrom(src => src.DecisionAuth))
                .ForPath(d => d.Decision.ECLI, opt => opt.MapFrom(src => src.DecisionEcli))
                .ForMember(d => d.DecisionRemarks, opt => opt.MapFrom(src => src.Descr))
                .ForMember(d => d.ValidFrom, opt => opt.MapFrom(src => src.DecisionDate))
                .ForMember(d => d.ValidFromSpecified, opt => opt.MapFrom(src => src.DecisionDate.HasValue))
                .ForMember(d => d.ReceiveDate, opt => opt.MapFrom(src => src.DecisionFinalDate))
                .ForMember(d => d.ReceiveDateSpecified, opt => opt.MapFrom(src => src.DecisionFinalDate.HasValue))
                .ReverseMap()
                .ForMember(d => d.DecisionChTypeId, opt => opt.MapFrom(src => CriminalRecordsReportResolver.EnumToString(src.DecisionChangeTypeReference)))
                .ForMember(d => d.DecisionNumber, opt => opt.MapFrom(src => src.Decision.FileNumber))
                .ForMember(d => d.DecisionFinalDate, opt => opt.MapFrom(src => src.Decision.DecisionFinalDate))
                .ForMember(d => d.DecisionDate, opt => opt.MapFrom(src => src.Decision.DecisionDate))
                .ForMember(d => d.DecisionAuth, opt => opt.MapFrom(src => src.Decision.DecidingAuthority))
                .ForMember(d => d.DecisionEcli, opt => opt.MapFrom(src => src.Decision.ECLI))
                .ForMember(d => d.Descr, opt => opt.MapFrom(src => src.DecisionRemarks))
                .ForMember(d => d.DecisionDate, opt => opt.MapFrom(src => src.ValidFrom))
                .ForMember(d => d.DecisionFinalDate, opt => opt.MapFrom(src => src.ReceiveDate))
                .ForMember(d => d.EntityState, opt => opt.MapFrom(src => EntityStateEnum.Added));

            CreateMap<PPerson, CriminalRecordsPersonDataType>()
                .ForPath(d => d.NamesBg.FirstName, opt => opt.MapFrom(src => src.Firstname))
                .ForPath(d => d.NamesBg.SurName, opt => opt.MapFrom(src => src.Surname))
                .ForPath(d => d.NamesBg.FamilyName, opt => opt.MapFrom(src => src.Familyname))
                .ForPath(d => d.NamesBg.FullName, opt => opt.MapFrom(src => src.FullnameLat))
                .ForPath(d => d.NamesEn.FirstName, opt => opt.MapFrom(src => src.FirstnameLat))
                .ForPath(d => d.NamesEn.SurName, opt => opt.MapFrom(src => src.SurnameLat))
                .ForPath(d => d.NamesEn.FamilyName, opt => opt.MapFrom(src => src.FamilynameLat))
                .ForPath(d => d.NamesEn.FullName, opt => opt.MapFrom(src => src.FullnameLat))
                .ForMember(d => d.Sex, opt => opt.MapFrom(src => src.Sex))
                .ForPath(d => d.IdentityNumber, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetPersonPids(src.PPersonIds)))
                .ForPath(d => d.BirthDate, opt => opt.MapFrom(src => CriminalRecordsReportResolver.GetDateType(src.BirthDate, src.BirthDatePrec)))
                .ForPath(d => d.BirthPlace.Country, opt => opt.MapFrom(src => src.BirthCountry))
                .ForPath(d => d.BirthPlace.City, opt => opt.MapFrom(src => src.BirthCity))
                .ForPath(d => d.BirthPlace.Descr, opt => opt.MapFrom(src => src.BirthPlaceOther))
                //.ForPath(d => d.PersonNationality, opt => opt.MapFrom(src => src.)) // todo: ? 
                .ForPath(d => d.MotherNames.FirstName, opt => opt.MapFrom(src => src.MotherFirstname))
                .ForPath(d => d.MotherNames.SurName, opt => opt.MapFrom(src => src.MotherSurname))
                .ForPath(d => d.MotherNames.FamilyName, opt => opt.MapFrom(src => src.MotherFamilyname))
                .ForPath(d => d.MotherNames.FullName, opt => opt.MapFrom(src => src.MotherFullname))
                .ForPath(d => d.FatherNames.FirstName, opt => opt.MapFrom(src => src.FatherFirstname))
                .ForPath(d => d.FatherNames.SurName, opt => opt.MapFrom(src => src.FatherSurname))
                .ForPath(d => d.FatherNames.FamilyName, opt => opt.MapFrom(src => src.FatherFamilyname))
                .ForPath(d => d.FatherNames.FullName, opt => opt.MapFrom(src => src.FatherFullname));
        }
    }
}
