<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2008 rel. 2 sp1 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:bul="http://cais.mjs.bg/BulletinModel-v1.0" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:n1="http://cais.mjs.bg/CriminalRecordsReportResponse-v1.0" xmlns:xdt="http://www.w3.org/2005/xpath-datatypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:altova="http://www.altova.com">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.0 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:decimal-format name="format1" grouping-separator=" " decimal-separator=","/>
	<xsl:template match="/">
		<html>
			<head>
				<title>
					<xsl:text>Свидетелство за съдимост</xsl:text>
				</title>
			</head>
			<body>
				<xsl:for-each select="$XML">
					<xsl:for-each select="n1:CriminalRecordsReport">
						<table border="0" cellpadding="0" cellspacing="0" width="100%">
							<tbody>
								<tr>
									<td>
										<span style="font-weight:bold; ">
											<xsl:text>РЕПУБЛИКА БЪЛГАРИЯ</xsl:text>
										</span>
									</td>
									<td align="right">
										<span>
											<xsl:text>Дата на издаване: </xsl:text>
										</span>
										<xsl:for-each select="n1:ReportDate">
											<span style="font-weight:bold; ">
												<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
												<xsl:text>.</xsl:text>
												<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
												<xsl:text>.</xsl:text>
												<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
												<xsl:text> </xsl:text>
												<xsl:value-of select="format-number(number(substring(string(string(.)), 12, 2)), '00', 'format1')"/>
												<xsl:text>:</xsl:text>
												<xsl:value-of select="format-number(number(substring(string(string(.)), 15, 2)), '00', 'format1')"/>
											</span>
										</xsl:for-each>
										<span>
											<xsl:text>&#160;</xsl:text>
										</span>
									</td>
								</tr>
								<tr>
									<td>
										<span>
											<xsl:text>ЦАИС &quot;СЪДЕБЕН СТАТУС&quot;</xsl:text>
										</span>
									</td>
									<td align="right" height="20">
										<xsl:for-each select="n1:ReportCriteria">
											<span>
												<xsl:text>За лице с </xsl:text>
											</span>
											<xsl:for-each select="bul:IdentifierType">
												<xsl:choose>
													<xsl:when test=". =&apos;EGN&apos;">
														<span>
															<xsl:text>ЕГН</xsl:text>
														</span>
													</xsl:when>
													<xsl:when test=". =&apos;LNCH&apos;">
														<span>
															<xsl:text>ЛНЧ</xsl:text>
														</span>
													</xsl:when>
													<xsl:when test=". =&apos;SUID&apos;">
														<span>
															<xsl:text>Системен идентификатор</xsl:text>
														</span>
													</xsl:when>
													<xsl:otherwise>
														<xsl:apply-templates/>
													</xsl:otherwise>
												</xsl:choose>
											</xsl:for-each>
											<xsl:for-each select="bul:PID">
												<span>
													<xsl:text>: </xsl:text>
												</span>
												<span style="font-weight:bold; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</xsl:for-each>
									</td>
								</tr>
								<tr>
									<td style="padding-top:0.75in; " align="center" colspan="2">
										<span>
											<xsl:text>ЕЛЕКТРОННА СПРАВКА ЗА СЪДИМОСТ</xsl:text>
										</span>
									</td>
								</tr>
								<tr>
									<td style="padding-bottom:0.2in; padding-top:0.2in; " colspan="2">
										<span>
											<xsl:text>УДОСТОВЕРЯВА, ЧЕ ЛИЦЕТО:</xsl:text>
										</span>
									</td>
								</tr>
								<tr>
									<td colspan="2" height="20">
										<span>
											<xsl:text>с </xsl:text>
										</span>
										<xsl:for-each select="n1:ReportCriteria">
											<xsl:for-each select="bul:IdentifierType">
												<xsl:choose>
													<xsl:when test=". =&apos;EGN&apos;">
														<span>
															<xsl:text>ЕГН</xsl:text>
														</span>
													</xsl:when>
													<xsl:when test=". =&apos;LNCH&apos;">
														<span>
															<xsl:text>ЛНЧ</xsl:text>
														</span>
													</xsl:when>
													<xsl:when test=". =&apos;SUID&apos;">
														<span>
															<xsl:text>Системен идентификатор</xsl:text>
														</span>
													</xsl:when>
													<xsl:otherwise>
														<xsl:apply-templates/>
													</xsl:otherwise>
												</xsl:choose>
											</xsl:for-each>
											<xsl:for-each select="bul:PID">
												<span>
													<xsl:text>: </xsl:text>
												</span>
												<span style="font-weight:bold; ">
													<xsl:apply-templates/>
												</span>
											</xsl:for-each>
										</xsl:for-each>
									</td>
								</tr>
								<tr>
									<td align="left" colspan="2" height="20">
										<xsl:for-each select="n1:ReportResult">
											<xsl:for-each select="n1:PersonData">
												<xsl:for-each select="bul:NamesBg">
													<table style="border-collapse:collapse; " border="0" width="100%">
														<tbody>
															<tr>
																<td align="left" width="200px">
																	<span>
																		<xsl:text>ИМЕНА НА КИРИЛИЦА:</xsl:text>
																	</span>
																</td>
																<td align="left">
																	<xsl:choose>
																		<xsl:when test="string-length(bul:FullName )=0">
																			<xsl:for-each select="bul:FirstName">
																				<span style="font-weight:bold; ">
																					<xsl:apply-templates/>
																				</span>
																			</xsl:for-each>
																			<xsl:for-each select="bul:SurName">
																				<span>
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<span style="font-weight:bold; ">
																					<xsl:apply-templates/>
																				</span>
																			</xsl:for-each>
																			<xsl:for-each select="bul:FamilyName">
																				<span>
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<span style="font-weight:bold; ">
																					<xsl:apply-templates/>
																				</span>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<xsl:for-each select="bul:FullName">
																				<span style="font-weight:bold; ">
																					<xsl:apply-templates/>
																				</span>
																			</xsl:for-each>
																		</xsl:otherwise>
																	</xsl:choose>
																</td>
															</tr>
														</tbody>
													</table>
												</xsl:for-each>
												<xsl:for-each select="bul:NamesEn">
													<table style="border-collapse:collapse; " border="0" width="100%">
														<tbody>
															<tr>
																<td align="left" width="200px">
																	<span>
																		<xsl:text>ИМЕНА НА ЛАТИНИЦА:</xsl:text>
																	</span>
																</td>
																<td align="left">
																	<xsl:choose>
																		<xsl:when test="string-length(bul:FullName )=0">
																			<xsl:for-each select="bul:FirstName">
																				<span style="font-weight:bold; ">
																					<xsl:apply-templates/>
																				</span>
																			</xsl:for-each>
																			<xsl:for-each select="bul:SurName">
																				<span>
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<span style="font-weight:bold; ">
																					<xsl:apply-templates/>
																				</span>
																			</xsl:for-each>
																			<xsl:for-each select="bul:FamilyName">
																				<span>
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<span style="font-weight:bold; ">
																					<xsl:apply-templates/>
																				</span>
																			</xsl:for-each>
																		</xsl:when>
																		<xsl:otherwise>
																			<xsl:for-each select="bul:FullName">
																				<span style="font-weight:bold; ">
																					<xsl:apply-templates/>
																				</span>
																			</xsl:for-each>
																		</xsl:otherwise>
																	</xsl:choose>
																</td>
															</tr>
														</tbody>
													</table>
												</xsl:for-each>
												<xsl:for-each select="bul:Sex">
													<table style="border-collapse:collapse; " border="0" width="100%">
														<tbody>
															<tr>
																<td align="left" width="200px">
																	<span>
																		<xsl:text>ПОЛ:</xsl:text>
																	</span>
																</td>
																<td align="left">
																	<xsl:choose>
																		<xsl:when test=". =1">
																			<span style="font-weight:bold; ">
																				<xsl:text>Мъж</xsl:text>
																			</span>
																		</xsl:when>
																		<xsl:when test=". =2">
																			<span style="font-weight:bold; ">
																				<xsl:text>Жена</xsl:text>
																			</span>
																		</xsl:when>
																		<xsl:when test=". =0">
																			<span style="font-weight:bold; ">
																				<xsl:text>Неизвестен</xsl:text>
																			</span>
																		</xsl:when>
																	</xsl:choose>
																</td>
															</tr>
														</tbody>
													</table>
												</xsl:for-each>
												<xsl:for-each select="bul:IdentityNumber">
													<table style="border-collapse:collapse; " border="0" width="100%">
														<tbody>
															<tr>
																<td align="left" width="200px">
																	<span>
																		<xsl:text>ИДЕНТИФИКАТОРИ:</xsl:text>
																	</span>
																</td>
																<td align="left">
																	<xsl:for-each select="bul:EGN">
																		<span>
																			<xsl:text>ЕГН: </xsl:text>
																		</span>
																		<span style="font-weight:bold; ">
																			<xsl:apply-templates/>
																		</span>
																		<span>
																			<xsl:text>;</xsl:text>
																		</span>
																	</xsl:for-each>
																	<xsl:for-each select="bul:LN">
																		<span>
																			<xsl:text>ЛН: </xsl:text>
																		</span>
																		<span style="font-weight:bold; ">
																			<xsl:apply-templates/>
																		</span>
																		<span>
																			<xsl:text>;</xsl:text>
																		</span>
																	</xsl:for-each>
																	<xsl:for-each select="bul:LNCh">
																		<span>
																			<xsl:text>ЛНЧ: </xsl:text>
																		</span>
																		<span style="font-weight:bold; ">
																			<xsl:apply-templates/>
																		</span>
																		<span>
																			<xsl:text>;</xsl:text>
																		</span>
																	</xsl:for-each>
																	<xsl:for-each select="bul:SUID">
																		<span>
																			<xsl:text>Системено ID: </xsl:text>
																		</span>
																		<span style="font-weight:bold; ">
																			<xsl:apply-templates/>
																		</span>
																		<span>
																			<xsl:text>;</xsl:text>
																		</span>
																	</xsl:for-each>
																</td>
															</tr>
														</tbody>
													</table>
												</xsl:for-each>
												<xsl:if test="string-length(  bul:BirthDate  ) + string-length(  bul:BirthPlace  ) &gt;0">
													<table style="border-collapse:collapse; " border="0" width="100%">
														<tbody>
															<tr>
																<td align="left" width="200px">
																	<span>
																		<xsl:text>РОДЕН(А):</xsl:text>
																	</span>
																</td>
																<td align="left">
																	<xsl:for-each select="bul:BirthDate">
																		<xsl:choose>
																			<xsl:when test="bul:DatePrecision =&apos;Y&apos;">
																				<xsl:for-each select="bul:Date">
																					<span style="font-weight:bold; ">
																						<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																					</span>
																					<span>
																						<xsl:text> година</xsl:text>
																					</span>
																				</xsl:for-each>
																			</xsl:when>
																			<xsl:when test="bul:DatePrecision =&apos;YM&apos;">
																				<xsl:for-each select="bul:Date">
																					<span style="font-weight:bold; ">
																						<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																					</span>
																					<span>
																						<xsl:text> месец </xsl:text>
																					</span>
																				</xsl:for-each>
																				<xsl:for-each select="bul:Date">
																					<span style="font-weight:bold; ">
																						<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																					</span>
																					<span>
																						<xsl:text> година</xsl:text>
																					</span>
																				</xsl:for-each>
																			</xsl:when>
																			<xsl:otherwise>
																				<xsl:for-each select="bul:Date">
																					<span style="font-weight:bold; ">
																						<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																						<xsl:text>.</xsl:text>
																						<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																						<xsl:text>.</xsl:text>
																						<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																					</span>
																					<span>
																						<xsl:text> г.</xsl:text>
																					</span>
																				</xsl:for-each>
																			</xsl:otherwise>
																		</xsl:choose>
																	</xsl:for-each>
																	<xsl:for-each select="bul:BirthPlace">
																		<xsl:for-each select="bul:Country">
																			<xsl:for-each select="bul:CountryName">
																				<span style="font-weight:bold; ">
																					<xsl:text>, </xsl:text>
																				</span>
																				<span style="font-weight:bold; ">
																					<xsl:apply-templates/>
																				</span>
																			</xsl:for-each>
																		</xsl:for-each>
																		<xsl:for-each select="bul:City">
																			<xsl:for-each select="bul:CityName">
																				<span>
																					<xsl:text>, </xsl:text>
																				</span>
																				<span style="font-weight:bold; ">
																					<xsl:apply-templates/>
																				</span>
																			</xsl:for-each>
																		</xsl:for-each>
																		<xsl:for-each select="bul:Descr">
																			<span>
																				<xsl:text>, </xsl:text>
																			</span>
																			<span style="font-weight:bold; ">
																				<xsl:apply-templates/>
																			</span>
																		</xsl:for-each>
																	</xsl:for-each>
																</td>
															</tr>
														</tbody>
													</table>
												</xsl:if>
												<table style="border-collapse:collapse; " border="0" width="100%">
													<tbody>
														<tr>
															<td align="left" width="200px">
																<span>
																	<xsl:text>ГРАЖДАНСТВО:</xsl:text>
																</span>
															</td>
															<td align="left">
																<xsl:for-each select="bul:PersonNationality">
																	<div>
																		<xsl:for-each select="bul:CountryName">
																			<span style="font-weight:bold; ">
																				<xsl:apply-templates/>
																			</span>
																		</xsl:for-each>
																		<xsl:for-each select="bul:CountryISOAlpha3">
																			<span>
																				<xsl:text>(</xsl:text>
																			</span>
																			<xsl:apply-templates/>
																			<span>
																				<xsl:text>)</xsl:text>
																			</span>
																		</xsl:for-each>
																	</div>
																</xsl:for-each>
															</td>
														</tr>
													</tbody>
												</table>
											</xsl:for-each>
											<xsl:for-each select="n1:BulletinsList">
												<xsl:choose>
													<xsl:when test="count( bul:Bulletin )=0">
														<div style="text-align:center; ">
															<span style="font-weight:bold; ">
																<xsl:text>НЕ Е ОСЪЖДАНО</xsl:text>
															</span>
														</div>
													</xsl:when>
													<xsl:otherwise>
														<div style="text-align:center; ">
															<span style="font-weight:bold; ">
																<xsl:text>Е ОСЪЖДАНО</xsl:text>
															</span>
														</div>
														<ol>
															<xsl:for-each select="bul:Bulletin">
																<li>
																	<span style="text-align:left; ">
																		<xsl:text>Дело </xsl:text>
																	</span>
																	<xsl:for-each select="bul:Conviction">
																		<xsl:for-each select="bul:CriminalCase">
																			<xsl:for-each select="bul:CaseNumber">
																				<span>
																					<xsl:text>№ </xsl:text>
																				</span>
																				<span style="font-weight:bold; ">
																					<xsl:apply-templates/>
																				</span>
																			</xsl:for-each>
																			<xsl:for-each select="bul:CaseYear">
																				<span>
																					<xsl:text>/</xsl:text>
																				</span>
																				<span style="font-weight:bold; ">
																					<xsl:apply-templates/>
																				</span>
																				<span>
																					<xsl:text> г.</xsl:text>
																				</span>
																			</xsl:for-each>
																			<xsl:for-each select="bul:CaseType">
																				<span>
																					<xsl:text>, </xsl:text>
																				</span>
																				<xsl:choose>
																					<xsl:when test=". =&apos;sign_and&apos;">
																						<span style="font-weight:bold; ">
																							<xsl:text>АНД</xsl:text>
																						</span>
																					</xsl:when>
																					<xsl:when test=".=&apos;sign_naxd&apos;">
																						<span style="font-weight:bold; ">
																							<xsl:text>НАХД</xsl:text>
																						</span>
																					</xsl:when>
																					<xsl:when test=".=&apos;sign_null&apos;"/>
																					<xsl:when test=".=&apos;sign_noxd&apos;">
																						<span style="font-weight:bold; ">
																							<xsl:text>НОХД</xsl:text>
																						</span>
																					</xsl:when>
																					<xsl:when test=".=&apos;sign_ncd&apos;">
																						<span style="font-weight:bold; ">
																							<xsl:text>НЧД</xsl:text>
																						</span>
																					</xsl:when>
																					<xsl:when test=".=&apos;sign_ncxd&apos;">
																						<span style="font-weight:bold; ">
																							<xsl:text>НЧХД</xsl:text>
																						</span>
																					</xsl:when>
																				</xsl:choose>
																			</xsl:for-each>
																			<xsl:for-each select="bul:CaseAuthority">
																				<xsl:for-each select="bul:DecidingAuthorityName">
																					<span>
																						<xsl:text> на </xsl:text>
																					</span>
																					<span style="font-weight:bold; ">
																						<xsl:apply-templates/>
																					</span>
																				</xsl:for-each>
																			</xsl:for-each>
																		</xsl:for-each>
																		<xsl:for-each select="bul:Decision">
																			<xsl:for-each select="bul:DecisionType">
																				<span>
																					<xsl:text>,&#160; </xsl:text>
																				</span>
																				<xsl:choose>
																					<xsl:when test=".=&apos;dkp_sporazumenie&apos;">
																						<span style="font-weight:bold; ">
																							<xsl:text>споразумение</xsl:text>
																						</span>
																					</xsl:when>
																					<xsl:when test=". =&apos;dkp_opredelenie&apos;">
																						<span style="font-weight:bold; ">
																							<xsl:text>определение</xsl:text>
																						</span>
																					</xsl:when>
																					<xsl:when test=".=&apos;dkp_prisada&apos;">
																						<span style="font-weight:bold; ">
																							<xsl:text>присъда</xsl:text>
																						</span>
																					</xsl:when>
																					<xsl:when test=".=&apos;dkp_reshenie&apos;">
																						<span style="font-weight:bold; ">
																							<xsl:text>решение</xsl:text>
																						</span>
																					</xsl:when>
																				</xsl:choose>
																			</xsl:for-each>
																			<xsl:for-each select="bul:FileNumber">
																				<span>
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<span style="font-weight:bold; ">
																					<xsl:apply-templates/>
																				</span>
																			</xsl:for-each>
																			<xsl:for-each select="bul:DecisionDate">
																				<xsl:if test=". !=&apos;0001-01-01&apos;">
																					<span>
																						<xsl:text>/</xsl:text>
																					</span>
																					<span style="font-weight:bold; ">
																						<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																						<xsl:text>.</xsl:text>
																						<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																						<xsl:text>.</xsl:text>
																						<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																					</span>
																					<span>
																						<xsl:text> г.</xsl:text>
																					</span>
																				</xsl:if>
																			</xsl:for-each>
																			<xsl:for-each select="bul:DecidingAuthority">
																				<xsl:for-each select="bul:DecidingAuthorityName">
																					<span>
																						<xsl:text> на </xsl:text>
																					</span>
																					<span style="font-weight:bold; ">
																						<xsl:apply-templates/>
																					</span>
																				</xsl:for-each>
																			</xsl:for-each>
																			<xsl:for-each select="bul:DecisionFinalDate">
																				<xsl:if test=". !=&apos;0001-01-01&apos;">
																					<span style="text-align:left; ">
																						<xsl:text>, в сила от </xsl:text>
																					</span>
																					<span style="font-weight:bold; ">
																						<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																						<xsl:text>.</xsl:text>
																						<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																						<xsl:text>.</xsl:text>
																						<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																					</span>
																					<span>
																						<xsl:text> г.</xsl:text>
																					</span>
																				</xsl:if>
																			</xsl:for-each>
																		</xsl:for-each>
																		<xsl:for-each select="bul:ConvictionRemarks">
																			<div>
																				<span style="font-weight:bold; ">
																					<xsl:apply-templates/>
																				</span>
																			</div>
																		</xsl:for-each>
																		<ul start="0">
																			<xsl:for-each select="bul:ConvictionOffence">
																				<li>
																					<span>
																						<xsl:text>Престъпление: </xsl:text>
																					</span>
																					<xsl:for-each select="bul:OffenceId">
																						<span>
																							<xsl:text>№ </xsl:text>
																						</span>
																						<span style="font-weight:bold; ">
																							<xsl:apply-templates/>
																						</span>
																						<span>
																							<xsl:text>&#160;</xsl:text>
																						</span>
																					</xsl:for-each>
																					<xsl:for-each select="bul:NationalCategoryTitle">
																						<span style="font-weight:bold; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																					<xsl:for-each select="bul:OffenceCommonCategoryReference">
																						<xsl:for-each select="bul:OffenceName">
																							<span>
																								<xsl:text>, </xsl:text>
																							</span>
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																					</xsl:for-each>
																					<xsl:for-each select="bul:Remarks">
																						<div>
																							<span>
																								<xsl:text>Описание на деянието: </xsl:text>
																							</span>
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</div>
																					</xsl:for-each>
																					<xsl:for-each select="bul:OffenceApplicableLegalProvisions">
																						<div>
																							<span>
																								<xsl:text>Приложими законови разпоредби: </xsl:text>
																							</span>
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</div>
																					</xsl:for-each>
																					<xsl:for-each select="bul:OffencePlace">
																						<span>
																							<xsl:text>Извършено на място: </xsl:text>
																						</span>
																						<xsl:for-each select="bul:Descr">
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																							<span>
																								<xsl:text>; </xsl:text>
																							</span>
																						</xsl:for-each>
																						<xsl:for-each select="bul:City">
																							<xsl:for-each select="bul:CityName">
																								<span style="font-weight:bold; ">
																									<xsl:apply-templates/>
																								</span>
																								<span>
																									<xsl:text>; </xsl:text>
																								</span>
																							</xsl:for-each>
																						</xsl:for-each>
																						<xsl:for-each select="bul:Country">
																							<xsl:for-each select="bul:CountryName">
																								<span style="font-weight:bold; ">
																									<xsl:apply-templates/>
																								</span>
																								<span>
																									<xsl:text>; </xsl:text>
																								</span>
																							</xsl:for-each>
																						</xsl:for-each>
																					</xsl:for-each>
																					<span style="text-align:left; ">
																						<xsl:text> извършено </xsl:text>
																					</span>
																					<xsl:for-each select="bul:OffenceStartDate">
																						<span>
																							<xsl:text>на </xsl:text>
																						</span>
																						<xsl:for-each select="bul:Date">
																							<xsl:if test=". !=&apos;0001-01-01&apos;">
																								<span style="font-weight:bold; ">
																									<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																									<xsl:text>.</xsl:text>
																									<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																									<xsl:text>.</xsl:text>
																									<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																								</span>
																								<span>
																									<xsl:text> г.</xsl:text>
																								</span>
																							</xsl:if>
																						</xsl:for-each>
																					</xsl:for-each>
																					<xsl:for-each select="bul:OffenceEndDate">
																						<span>
																							<xsl:text>&#160;</xsl:text>
																						</span>
																						<span style="text-align:left; ">
																							<xsl:text>до</xsl:text>
																						</span>
																						<span>
																							<xsl:text>&#160;</xsl:text>
																						</span>
																						<xsl:for-each select="bul:Date">
																							<xsl:if test=". !=&apos;0001-01-01&apos;">
																								<span style="font-weight:bold; ">
																									<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																									<xsl:text>.</xsl:text>
																									<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																									<xsl:text>.</xsl:text>
																									<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																								</span>
																								<span>
																									<xsl:text> г.</xsl:text>
																								</span>
																							</xsl:if>
																						</xsl:for-each>
																					</xsl:for-each>
																					<span>
																						<xsl:text> - </xsl:text>
																					</span>
																					<span style="font-weight:bold; ">
																						<xsl:text>УМИШЛЕНО</xsl:text>
																					</span>
																					<xsl:for-each select="bul:FormOfGuilt">
																						<span>
																							<xsl:text> - </xsl:text>
																						</span>
																						<xsl:choose>
																							<xsl:when test=". =&apos;intentionally&apos;">
																								<span style="font-weight:bold; ">
																									<xsl:text>УМИШЛЕНО</xsl:text>
																								</span>
																							</xsl:when>
																							<xsl:when test=". =&apos;recklessly&apos;">
																								<span style="font-weight:bold; ">
																									<xsl:text>НЕПРЕДПАЗЛИВО</xsl:text>
																								</span>
																							</xsl:when>
																						</xsl:choose>
																					</xsl:for-each>
																					<br/>
																				</li>
																			</xsl:for-each>
																		</ul>
																		<xsl:for-each select="bul:ConvictionSanction">
																			<ul type="square">
																				<li>
																					<div>
																						<span>
																							<xsl:text>Наказание: </xsl:text>
																						</span>
																						<xsl:for-each select="bul:SanctionId">
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																							<span>
																								<xsl:text>&#160;</xsl:text>
																							</span>
																						</xsl:for-each>
																						<xsl:for-each select="bul:NationalCategoryTitle">
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																						<xsl:for-each select="bul:SanctionCommonCategoryReference">
																							<xsl:for-each select="bul:SanctionText">
																								<span>
																									<xsl:text>, от категория: </xsl:text>
																								</span>
																								<span style="font-weight:bold; ">
																									<xsl:apply-templates/>
																								</span>
																							</xsl:for-each>
																						</xsl:for-each>
																						<xsl:choose>
																							<xsl:when test="bul:NationalCategoryCode =&apos;nkz_globa&apos;">
																								<xsl:for-each select="bul:Fine">
																									<xsl:for-each select="bul:SanctionAmountOfIndividualFine">
																										<span>
																											<xsl:text>, </xsl:text>
																										</span>
																										<span style="text-align:left; ">
																											<xsl:text>в размер на </xsl:text>
																										</span>
																										<span style="font-weight:bold; ">
																											<xsl:apply-templates/>
																										</span>
																										<span>
																											<xsl:text> лв.</xsl:text>
																										</span>
																									</xsl:for-each>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="bul:NationalCategoryCode =&apos;nkz_probacia&apos;">
																								<xsl:for-each select="bul:Probation">
																									<ul type="circle">
																										<li>
																											<div>
																												<xsl:for-each select="bul:ProbationCategoryTitle">
																													<span style="font-weight:bold; ">
																														<xsl:apply-templates/>
																													</span>
																												</xsl:for-each>
																												<xsl:for-each select="bul:ProbationValue">
																													<span>
																														<xsl:text> - </xsl:text>
																													</span>
																													<span style="font-weight:bold; ">
																														<xsl:apply-templates/>
																													</span>
																												</xsl:for-each>
																												<xsl:for-each select="bul:ProbationMeasureTitle">
																													<span>
																														<xsl:text>&#160;</xsl:text>
																													</span>
																													<span style="font-weight:bold; ">
																														<xsl:apply-templates/>
																													</span>
																												</xsl:for-each>
																												<xsl:for-each select="bul:SanctionSentencedPeriod">
																													<span>
																														<xsl:text>&#160;</xsl:text>
																													</span>
																													<span style="text-align:left; ">
																														<xsl:text>за срок от</xsl:text>
																													</span>
																													<span>
																														<xsl:text>&#160; </xsl:text>
																													</span>
																													<span style="font-weight:bold; ">
																														<xsl:variable name="sDurationYear">
																															<xsl:call-template name="DurationToYear">
																																<xsl:with-param name="sDuration" select="string(string(.))"/>
																															</xsl:call-template>
																														</xsl:variable>
																														<xsl:value-of select="format-number(number($sDurationYear), '0', 'format1')"/>
																													</span>
																													<span>
																														<xsl:text> г. </xsl:text>
																													</span>
																													<span style="font-weight:bold; ">
																														<xsl:variable name="sDurationMonth">
																															<xsl:call-template name="DurationToMonth">
																																<xsl:with-param name="sDuration" select="string(.)"/>
																															</xsl:call-template>
																														</xsl:variable>
																														<xsl:value-of select="format-number(number($sDurationMonth), '0', 'format1')"/>
																													</span>
																													<span>
																														<xsl:text> м. </xsl:text>
																													</span>
																													<span style="font-weight:bold; ">
																														<xsl:variable name="sDurationDay">
																															<xsl:call-template name="DurationToDay">
																																<xsl:with-param name="sDuration" select="string(.)"/>
																															</xsl:call-template>
																														</xsl:variable>
																														<xsl:value-of select="format-number(number($sDurationDay), '0', 'format1')"/>
																													</span>
																													<span>
																														<xsl:text> д. </xsl:text>
																													</span>
																													<span style="font-weight:bold; ">
																														<xsl:variable name="sDurationHour">
																															<xsl:call-template name="DurationToHour">
																																<xsl:with-param name="sDuration" select="string(.)"/>
																															</xsl:call-template>
																														</xsl:variable>
																														<xsl:value-of select="format-number(number($sDurationHour), '0', 'format1')"/>
																													</span>
																													<span>
																														<xsl:text> ч.</xsl:text>
																													</span>
																												</xsl:for-each>
																											</div>
																										</li>
																									</ul>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:when test="bul:NationalCategoryCode = &apos;nkz_lishavane_ot_svoboda&apos;">
																								<xsl:for-each select="bul:Prison">
																									<div>
																										<xsl:for-each select="bul:SanctionSentencedPeriod">
																											<span>
																												<xsl:text>&#160;</xsl:text>
																											</span>
																											<span style="text-align:left; ">
																												<xsl:text>за срок от</xsl:text>
																											</span>
																											<span>
																												<xsl:text>&#160; </xsl:text>
																											</span>
																											<span style="font-weight:bold; ">
																												<xsl:variable name="sDurationYear">
																													<xsl:call-template name="DurationToYear">
																														<xsl:with-param name="sDuration" select="string(string(.))"/>
																													</xsl:call-template>
																												</xsl:variable>
																												<xsl:value-of select="format-number(number($sDurationYear), '0', 'format1')"/>
																											</span>
																											<span>
																												<xsl:text> г. </xsl:text>
																											</span>
																											<span style="font-weight:bold; ">
																												<xsl:variable name="sDurationMonth">
																													<xsl:call-template name="DurationToMonth">
																														<xsl:with-param name="sDuration" select="string(.)"/>
																													</xsl:call-template>
																												</xsl:variable>
																												<xsl:value-of select="format-number(number($sDurationMonth), '0', 'format1')"/>
																											</span>
																											<span>
																												<xsl:text> м. </xsl:text>
																											</span>
																											<span style="font-weight:bold; ">
																												<xsl:variable name="sDurationDay">
																													<xsl:call-template name="DurationToDay">
																														<xsl:with-param name="sDuration" select="string(.)"/>
																													</xsl:call-template>
																												</xsl:variable>
																												<xsl:value-of select="format-number(number($sDurationDay), '0', 'format1')"/>
																											</span>
																											<span>
																												<xsl:text> д. </xsl:text>
																											</span>
																											<span style="font-weight:bold; ">
																												<xsl:variable name="sDurationHour">
																													<xsl:call-template name="DurationToHour">
																														<xsl:with-param name="sDuration" select="string(.)"/>
																													</xsl:call-template>
																												</xsl:variable>
																												<xsl:value-of select="format-number(number($sDurationHour), '0', 'format1')"/>
																											</span>
																											<span>
																												<xsl:text> ч.</xsl:text>
																											</span>
																										</xsl:for-each>
																										<xsl:for-each select="bul:SanctionSuspension">
																											<div>
																												<span style="text-align:left; ">
																													<xsl:text>Освобождаването от изтърпяване на наказанието и неналагането на наказание съгласно НК, както и условното осъждане по чл. 66 ал.1 или чл.69, ал1 НК за срок от </xsl:text>
																												</span>
																												<span>
																													<xsl:text>&#160;</xsl:text>
																												</span>
																												<span style="text-align:left; ">
																													<xsl:text>за срок от</xsl:text>
																												</span>
																												<span>
																													<xsl:text>&#160; </xsl:text>
																												</span>
																												<span style="font-weight:bold; ">
																													<xsl:variable name="sDurationYear">
																														<xsl:call-template name="DurationToYear">
																															<xsl:with-param name="sDuration" select="string(string(.))"/>
																														</xsl:call-template>
																													</xsl:variable>
																													<xsl:value-of select="format-number(number($sDurationYear), '0', 'format1')"/>
																												</span>
																												<span>
																													<xsl:text> г. </xsl:text>
																												</span>
																												<span style="font-weight:bold; ">
																													<xsl:variable name="sDurationMonth">
																														<xsl:call-template name="DurationToMonth">
																															<xsl:with-param name="sDuration" select="string(.)"/>
																														</xsl:call-template>
																													</xsl:variable>
																													<xsl:value-of select="format-number(number($sDurationMonth), '0', 'format1')"/>
																												</span>
																												<span>
																													<xsl:text> м. </xsl:text>
																												</span>
																												<span style="font-weight:bold; ">
																													<xsl:variable name="sDurationDay">
																														<xsl:call-template name="DurationToDay">
																															<xsl:with-param name="sDuration" select="string(.)"/>
																														</xsl:call-template>
																													</xsl:variable>
																													<xsl:value-of select="format-number(number($sDurationDay), '0', 'format1')"/>
																												</span>
																												<span>
																													<xsl:text> д.</xsl:text>
																												</span>
																											</div>
																										</xsl:for-each>
																										<xsl:for-each select="bul:DetentionDescription">
																											<span style="font-weight:bold; ">
																												<xsl:apply-templates/>
																											</span>
																										</xsl:for-each>
																									</div>
																								</xsl:for-each>
																							</xsl:when>
																							<xsl:otherwise>
																								<xsl:for-each select="bul:Other">
																									<xsl:for-each select="bul:SanctionSentencedPeriodLength">
																										<span style="text-align:left; ">
																											<xsl:text>за срок от</xsl:text>
																										</span>
																										<span>
																											<xsl:text>&#160; </xsl:text>
																										</span>
																										<span style="font-weight:bold; ">
																											<xsl:variable name="sDurationYear">
																												<xsl:call-template name="DurationToYear">
																													<xsl:with-param name="sDuration" select="string(string(.))"/>
																												</xsl:call-template>
																											</xsl:variable>
																											<xsl:value-of select="format-number(number($sDurationYear), '0', 'format1')"/>
																										</span>
																										<span>
																											<xsl:text> г. </xsl:text>
																										</span>
																										<span style="font-weight:bold; ">
																											<xsl:variable name="sDurationMonth">
																												<xsl:call-template name="DurationToMonth">
																													<xsl:with-param name="sDuration" select="string(.)"/>
																												</xsl:call-template>
																											</xsl:variable>
																											<xsl:value-of select="format-number(number($sDurationMonth), '0', 'format1')"/>
																										</span>
																										<span>
																											<xsl:text> м. </xsl:text>
																										</span>
																										<span style="font-weight:bold; ">
																											<xsl:variable name="sDurationDay">
																												<xsl:call-template name="DurationToDay">
																													<xsl:with-param name="sDuration" select="string(.)"/>
																												</xsl:call-template>
																											</xsl:variable>
																											<xsl:value-of select="format-number(number($sDurationDay), '0', 'format1')"/>
																										</span>
																										<span>
																											<xsl:text> д. </xsl:text>
																										</span>
																									</xsl:for-each>
																								</xsl:for-each>
																							</xsl:otherwise>
																						</xsl:choose>
																						<xsl:for-each select="bul:Remarks">
																							<div>
																								<span style="font-weight:bold; ">
																									<xsl:apply-templates/>
																								</span>
																							</div>
																						</xsl:for-each>
																					</div>
																				</li>
																			</ul>
																		</xsl:for-each>
																		<xsl:if test="bul:ServingPrevSuspendedSentence = &apos;true&apos;">
																			<xsl:for-each select="bul:ServingPrevSuspendedSentence">
																				<span style="font-weight:bold; ">
																					<xsl:text>Постановено изтърпяване на предходна условна присъда</xsl:text>
																				</span>
																			</xsl:for-each>
																			<xsl:for-each select="bul:ServingPrevSuspendedSentenceActNumber">
																				<span>
																					<xsl:text>: </xsl:text>
																				</span>
																				<xsl:apply-templates/>
																			</xsl:for-each>
																		</xsl:if>
																		<xsl:if test="count(  bul:ConvictionDecisions )&gt; 0">
																			<div>
																				<span>
																					<xsl:text>Допълнителни сведения: </xsl:text>
																				</span>
																			</div>
																		</xsl:if>
																		<xsl:if test="count(bul:ConvictionDecisions )&gt;0">
																			<xsl:for-each select="bul:ConvictionDecisions">
																				<ul type="circle">
																					<li>
																						<xsl:for-each select="bul:DecisionChangeTypeReference">
																							<xsl:choose>
																								<xsl:when test=". =&apos;DCH-00-R&apos;">
																									<span style="font-weight:bold; ">
																										<xsl:text>Реабилитация</xsl:text>
																									</span>
																								</xsl:when>
																								<xsl:when test=". =&apos;DCH-00-N&apos;">
																									<span style="font-weight:bold; ">
																										<xsl:text>Край на изтърпяването на наказанието</xsl:text>
																									</span>
																								</xsl:when>
																								<xsl:when test=". =&apos;DCH-00-E&apos;">
																									<span style="font-weight:bold; ">
																										<xsl:text>Замяна на наказание/мярка</xsl:text>
																									</span>
																								</xsl:when>
																								<xsl:when test=". =&apos;DCH-00-I&apos;">
																									<span style="font-weight:bold; ">
																										<xsl:text>Последващо определяне на едно общо наказание</xsl:text>
																									</span>
																								</xsl:when>
																								<xsl:when test=". =&apos;DCH-00-Q&apos;">
																									<span style="font-weight:bold; ">
																										<xsl:text>Допуснато условно предсрочно освобождаване</xsl:text>
																									</span>
																								</xsl:when>
																								<xsl:when test=". =&apos;DCH-00-S&apos;">
																									<span style="font-weight:bold; ">
																										<xsl:text>Отмяна на условно предсрочно освобождаване</xsl:text>
																									</span>
																								</xsl:when>
																								<xsl:when test=". =&apos;DCH-00-Y&apos;">
																									<span style="font-weight:bold; ">
																										<xsl:text>Постановен съдебен акт по чл. 425 НПК</xsl:text>
																									</span>
																								</xsl:when>
																								<xsl:when test=". =&apos;DCH-88-B&apos;">
																									<span style="font-weight:bold; ">
																										<xsl:text>Отменена кумулация</xsl:text>
																									</span>
																								</xsl:when>
																								<xsl:when test=". =&apos;DCH-88-A&apos;">
																									<span style="font-weight:bold; ">
																										<xsl:text>Погасено по давност по наказание – изтича срока чл. 82 от НК</xsl:text>
																									</span>
																								</xsl:when>
																								<xsl:when test=". =&apos;DCH-00-P&apos;">
																									<span style="font-weight:bold; ">
																										<xsl:text>Амнистия</xsl:text>
																									</span>
																								</xsl:when>
																								<xsl:when test=". =&apos;DCH-00-O&apos;">
																									<span style="font-weight:bold; ">
																										<xsl:text>Помилване</xsl:text>
																									</span>
																								</xsl:when>
																							</xsl:choose>
																						</xsl:for-each>
																						<xsl:for-each select="bul:ValidFrom">
																							<xsl:if test=". !=&apos;0001-01-01&apos;">
																								<span>
																									<xsl:text>, валидно от </xsl:text>
																								</span>
																								<span style="font-weight:bold; ">
																									<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																									<xsl:text>.</xsl:text>
																									<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																									<xsl:text>.</xsl:text>
																									<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																								</span>
																								<span>
																									<xsl:text> г.</xsl:text>
																								</span>
																							</xsl:if>
																						</xsl:for-each>
																						<xsl:for-each select="bul:ReceiveDate">
																							<xsl:if test=". !=&apos;0001-01-01&apos;">
																								<span>
																									<xsl:text>, дата на получаване на сведението: </xsl:text>
																								</span>
																								<span style="font-weight:bold; ">
																									<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																									<xsl:text>.</xsl:text>
																									<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																									<xsl:text>.</xsl:text>
																									<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																								</span>
																								<span>
																									<xsl:text> г.</xsl:text>
																								</span>
																							</xsl:if>
																						</xsl:for-each>
																						<xsl:for-each select="bul:Decision">
																							<xsl:for-each select="bul:DecisionType">
																								<span>
																									<xsl:text>, </xsl:text>
																								</span>
																								<xsl:choose>
																									<xsl:when test=".=&apos;dkp_sporazumenie&apos;">
																										<span style="font-weight:bold; ">
																											<xsl:text>споразумение</xsl:text>
																										</span>
																									</xsl:when>
																									<xsl:when test=". =&apos;dkp_opredelenie&apos;">
																										<span style="font-weight:bold; ">
																											<xsl:text>определение</xsl:text>
																										</span>
																									</xsl:when>
																									<xsl:when test=".=&apos;dkp_prisada&apos;">
																										<span style="font-weight:bold; ">
																											<xsl:text>присъда</xsl:text>
																										</span>
																									</xsl:when>
																									<xsl:when test=".=&apos;dkp_reshenie&apos;">
																										<span style="font-weight:bold; ">
																											<xsl:text>решение</xsl:text>
																										</span>
																									</xsl:when>
																								</xsl:choose>
																							</xsl:for-each>
																							<xsl:for-each select="bul:FileNumber">
																								<span>
																									<xsl:text> № </xsl:text>
																								</span>
																								<span style="font-weight:bold; ">
																									<xsl:apply-templates/>
																								</span>
																							</xsl:for-each>
																							<xsl:for-each select="bul:DecisionDate">
																								<xsl:if test=". !=&apos;0001-01-01&apos;">
																									<span>
																										<xsl:text>/</xsl:text>
																									</span>
																									<span style="font-weight:bold; ">
																										<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																										<xsl:text>.</xsl:text>
																										<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																										<xsl:text>.</xsl:text>
																										<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																									</span>
																									<span>
																										<xsl:text> г.</xsl:text>
																									</span>
																								</xsl:if>
																								<span>
																									<xsl:text>&#160;</xsl:text>
																								</span>
																							</xsl:for-each>
																							<xsl:for-each select="bul:DecidingAuthority">
																								<xsl:for-each select="bul:DecidingAuthorityName">
																									<span>
																										<xsl:text> на </xsl:text>
																									</span>
																									<span style="font-weight:bold; ">
																										<xsl:apply-templates/>
																									</span>
																								</xsl:for-each>
																							</xsl:for-each>
																							<xsl:for-each select="bul:DecisionFinalDate">
																								<xsl:if test=". !=&apos;0001-01-01&apos;">
																									<span style="text-align:left; ">
																										<xsl:text>, в сила от </xsl:text>
																									</span>
																									<span style="font-weight:bold; ">
																										<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																										<xsl:text>.</xsl:text>
																										<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																										<xsl:text>.</xsl:text>
																										<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																									</span>
																									<span>
																										<xsl:text> г.</xsl:text>
																									</span>
																								</xsl:if>
																							</xsl:for-each>
																						</xsl:for-each>
																						<xsl:for-each select="bul:DecisionRemarks">
																							<div>
																								<xsl:apply-templates/>
																							</div>
																						</xsl:for-each>
																					</li>
																				</ul>
																			</xsl:for-each>
																		</xsl:if>
																	</xsl:for-each>
																	<xsl:for-each select="bul:IssuerData">
																		<xsl:if test="string-length(bul:BulletinCreateDate )&gt;0 or  string-length(bul:BulletinCreatorPerson/bul:Names )&gt;0 or  string-length( bul:BulletinApproverPerson/bul:Names )&gt;0 or string-length( bul:BulletinCreatorAuthority/bul:DecidingAuthorityName) &gt; 0">
																			<span>
																				<xsl:text>Бюлетин</xsl:text>
																			</span>
																		</xsl:if>
																		<xsl:for-each select="bul:BulletinCreatorAuthority">
																			<xsl:for-each select="bul:DecidingAuthorityName">
																				<span>
																					<xsl:text> издаден от </xsl:text>
																				</span>
																				<span style="font-weight:bold; ">
																					<xsl:apply-templates/>
																				</span>
																			</xsl:for-each>
																		</xsl:for-each>
																		<xsl:for-each select="bul:BulletinCreateDate">
																			<xsl:if test=". !=&apos;0001-01-01&apos; and . != &apos;0001-01-01T00:00:00&apos;">
																				<span>
																					<xsl:text>, издаден на </xsl:text>
																				</span>
																				<span style="font-weight:bold; ">
																					<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																					<xsl:text>.</xsl:text>
																					<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																					<xsl:text>.</xsl:text>
																					<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																				</span>
																				<span>
																					<xsl:text> г.</xsl:text>
																				</span>
																			</xsl:if>
																		</xsl:for-each>
																	</xsl:for-each>
																	<xsl:for-each select="bul:RegistrationData">
																		<xsl:for-each select="bul:ConvictionStatusAuthority">
																			<xsl:for-each select="bul:Name">
																				<span>
																					<xsl:text>, който се съхранява в </xsl:text>
																				</span>
																				<span style="font-weight:bold; ">
																					<xsl:apply-templates/>
																				</span>
																			</xsl:for-each>
																		</xsl:for-each>
																		<xsl:for-each select="bul:RegistrationNumber">
																			<span>
																				<xsl:text>, с рег. № </xsl:text>
																			</span>
																			<span style="font-weight:bold; ">
																				<xsl:apply-templates/>
																			</span>
																		</xsl:for-each>
																		<xsl:for-each select="bul:BulletinReceivedDate">
																			<xsl:if test=". !=&apos;0001-01-01&apos; or . != &apos;0001-01-01T00:00:00&apos;">
																				<span>
																					<xsl:text>, с дата на регистрация </xsl:text>
																				</span>
																				<span style="font-weight:bold; ">
																					<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																					<xsl:text>.</xsl:text>
																					<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																					<xsl:text>.</xsl:text>
																					<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																				</span>
																				<span>
																					<xsl:text> г.</xsl:text>
																				</span>
																			</xsl:if>
																		</xsl:for-each>
																	</xsl:for-each>
																	<xsl:for-each select="bul:Person">
																		<div>
																			<span>
																				<xsl:text>Лични данни в бюлетина: </xsl:text>
																			</span>
																			<xsl:for-each select="bul:NamesBg">
																				<xsl:choose>
																					<xsl:when test="string-length(bul:FullName )=0">
																						<xsl:for-each select="bul:FirstName">
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																						<xsl:for-each select="bul:SurName">
																							<span>
																								<xsl:text>&#160;</xsl:text>
																							</span>
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																						<xsl:for-each select="bul:FamilyName">
																							<span>
																								<xsl:text>&#160;</xsl:text>
																							</span>
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																					</xsl:when>
																					<xsl:otherwise>
																						<xsl:for-each select="bul:FullName">
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																					</xsl:otherwise>
																				</xsl:choose>
																			</xsl:for-each>
																			<xsl:for-each select="bul:NamesEn">
																				<xsl:choose>
																					<xsl:when test="string-length(bul:FullName )=0">
																						<span>
																							<xsl:text> / </xsl:text>
																						</span>
																						<xsl:for-each select="bul:FirstName">
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																						<xsl:for-each select="bul:SurName">
																							<span>
																								<xsl:text>&#160;</xsl:text>
																							</span>
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																						<xsl:for-each select="bul:FamilyName">
																							<span>
																								<xsl:text>&#160;</xsl:text>
																							</span>
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																					</xsl:when>
																					<xsl:otherwise>
																						<xsl:for-each select="bul:FullName">
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																					</xsl:otherwise>
																				</xsl:choose>
																			</xsl:for-each>
																			<xsl:for-each select="bul:Sex">
																				<xsl:choose>
																					<xsl:when test=". =1">
																						<span>
																							<xsl:text>, пол: </xsl:text>
																						</span>
																						<span style="font-weight:bold; ">
																							<xsl:text>Мъж</xsl:text>
																						</span>
																					</xsl:when>
																					<xsl:when test=". =2">
																						<span>
																							<xsl:text>, пол: </xsl:text>
																						</span>
																						<span style="font-weight:bold; ">
																							<xsl:text>Жена</xsl:text>
																						</span>
																					</xsl:when>
																					<xsl:when test=". =0">
																						<span>
																							<xsl:text>, пол: </xsl:text>
																						</span>
																						<span style="font-weight:bold; ">
																							<xsl:text>Неизвестен</xsl:text>
																						</span>
																					</xsl:when>
																				</xsl:choose>
																			</xsl:for-each>
																			<xsl:for-each select="bul:IdentityNumber">
																				<xsl:for-each select="bul:EGN">
																					<span>
																						<xsl:text>, ЕГН: </xsl:text>
																					</span>
																					<span style="font-weight:bold; ">
																						<xsl:apply-templates/>
																					</span>
																				</xsl:for-each>
																				<xsl:for-each select="bul:LN">
																					<span>
																						<xsl:text>, ЛН: </xsl:text>
																					</span>
																					<span style="font-weight:bold; ">
																						<xsl:apply-templates/>
																					</span>
																				</xsl:for-each>
																				<xsl:for-each select="bul:LNCh">
																					<span>
																						<xsl:text>, ЛНЧ: </xsl:text>
																					</span>
																					<span style="font-weight:bold; ">
																						<xsl:apply-templates/>
																					</span>
																				</xsl:for-each>
																				<xsl:for-each select="bul:SUID">
																					<span>
																						<xsl:text>, Системено ID: </xsl:text>
																					</span>
																					<span style="font-weight:bold; ">
																						<xsl:apply-templates/>
																					</span>
																				</xsl:for-each>
																			</xsl:for-each>
																			<xsl:for-each select="bul:BirthDate">
																				<span>
																					<xsl:text>, роден/а: </xsl:text>
																				</span>
																				<xsl:choose>
																					<xsl:when test="bul:DatePrecision =&apos;Y&apos;">
																						<xsl:for-each select="bul:Date">
																							<span style="font-weight:bold; ">
																								<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																							</span>
																							<span>
																								<xsl:text> година</xsl:text>
																							</span>
																						</xsl:for-each>
																					</xsl:when>
																					<xsl:when test="bul:DatePrecision =&apos;YM&apos;">
																						<xsl:for-each select="bul:Date">
																							<span style="font-weight:bold; ">
																								<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																							</span>
																							<span>
																								<xsl:text> месец </xsl:text>
																							</span>
																						</xsl:for-each>
																						<xsl:for-each select="bul:Date">
																							<span style="font-weight:bold; ">
																								<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																							</span>
																							<span>
																								<xsl:text> година</xsl:text>
																							</span>
																						</xsl:for-each>
																					</xsl:when>
																					<xsl:otherwise>
																						<xsl:for-each select="bul:Date">
																							<span style="font-weight:bold; ">
																								<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																								<xsl:text>.</xsl:text>
																								<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																								<xsl:text>.</xsl:text>
																								<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																							</span>
																							<span>
																								<xsl:text> г.</xsl:text>
																							</span>
																						</xsl:for-each>
																					</xsl:otherwise>
																				</xsl:choose>
																			</xsl:for-each>
																			<xsl:for-each select="bul:BirthPlace">
																				<xsl:for-each select="bul:Country">
																					<xsl:for-each select="bul:CountryName">
																						<span style="font-weight:bold; ">
																							<xsl:text>, </xsl:text>
																						</span>
																						<span style="font-weight:bold; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																				</xsl:for-each>
																				<xsl:for-each select="bul:City">
																					<xsl:for-each select="bul:CityName">
																						<span>
																							<xsl:text>, </xsl:text>
																						</span>
																						<span style="font-weight:bold; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																				</xsl:for-each>
																				<xsl:for-each select="bul:Descr">
																					<span>
																						<xsl:text>, </xsl:text>
																					</span>
																					<span style="font-weight:bold; ">
																						<xsl:apply-templates/>
																					</span>
																				</xsl:for-each>
																			</xsl:for-each>
																			<xsl:for-each select="bul:MotherNames">
																				<span>
																					<xsl:text>, майка: </xsl:text>
																				</span>
																				<xsl:choose>
																					<xsl:when test="string-length(bul:FullName )=0">
																						<xsl:for-each select="bul:FirstName">
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																						<xsl:for-each select="bul:SurName">
																							<span>
																								<xsl:text>&#160;</xsl:text>
																							</span>
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																						<xsl:for-each select="bul:FamilyName">
																							<span>
																								<xsl:text>&#160;</xsl:text>
																							</span>
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																					</xsl:when>
																					<xsl:otherwise>
																						<xsl:for-each select="bul:FullName">
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																					</xsl:otherwise>
																				</xsl:choose>
																			</xsl:for-each>
																			<xsl:for-each select="bul:FatherNames">
																				<span>
																					<xsl:text>, баща: </xsl:text>
																				</span>
																				<xsl:choose>
																					<xsl:when test="string-length(bul:FullName )=0">
																						<xsl:for-each select="bul:FirstName">
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																						<xsl:for-each select="bul:SurName">
																							<span>
																								<xsl:text>&#160;</xsl:text>
																							</span>
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																						<xsl:for-each select="bul:FamilyName">
																							<span>
																								<xsl:text>&#160;</xsl:text>
																							</span>
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																					</xsl:when>
																					<xsl:otherwise>
																						<xsl:for-each select="bul:FullName">
																							<span style="font-weight:bold; ">
																								<xsl:apply-templates/>
																							</span>
																						</xsl:for-each>
																					</xsl:otherwise>
																				</xsl:choose>
																			</xsl:for-each>
																		</div>
																	</xsl:for-each>
																</li>
															</xsl:for-each>
														</ol>
													</xsl:otherwise>
												</xsl:choose>
											</xsl:for-each>
										</xsl:for-each>
									</td>
								</tr>
							</tbody>
						</table>
					</xsl:for-each>
				</xsl:for-each>
			</body>
		</html>
	</xsl:template>
	<xsl:template name="DurationToYear">
		<xsl:param name="sDuration"/>
		<xsl:variable name="sDate">
			<xsl:choose>
				<xsl:when test="contains(string($sDuration), 'T')">
					<xsl:value-of select="substring-before(string($sDuration), 'T')"/>
				</xsl:when>
				<xsl:otherwise>
					<xsl:value-of select="string($sDuration)"/>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:variable>
		<xsl:variable name="sYear" select="substring-before(substring-after($sDate, 'P'), 'Y')"/>
		<xsl:choose>
			<xsl:when test="string-length($sYear)=0">
				<xsl:value-of select="'0'"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="concat(substring-before(string($sDuration), 'P'), $sYear)"/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<xsl:template name="DurationToMonth">
		<xsl:param name="sDuration"/>
		<xsl:variable name="sDate">
			<xsl:choose>
				<xsl:when test="contains(string($sDuration), 'T')">
					<xsl:value-of select="substring-before(string($sDuration), 'T')"/>
				</xsl:when>
				<xsl:otherwise>
					<xsl:value-of select="string($sDuration)"/>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:variable>
		<xsl:variable name="sMonth">
			<xsl:choose>
				<xsl:when test="contains($sDate, 'Y')">
					<xsl:value-of select="substring-before(substring-after($sDate, 'Y'), 'M')"/>
				</xsl:when>
				<xsl:otherwise>
					<xsl:value-of select="substring-before(substring-after($sDate, 'P'), 'M')"/>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:variable>
		<xsl:choose>
			<xsl:when test="string-length($sMonth)=0">
				<xsl:value-of select="'0'"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="concat(substring-before(string($sDuration), 'P'), $sMonth)"/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<xsl:template name="DurationToDay">
		<xsl:param name="sDuration"/>
		<xsl:variable name="sDate">
			<xsl:choose>
				<xsl:when test="contains(string($sDuration), 'T')">
					<xsl:value-of select="substring-before(string($sDuration), 'T')"/>
				</xsl:when>
				<xsl:otherwise>
					<xsl:value-of select="string($sDuration)"/>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:variable>
		<xsl:variable name="sDay">
			<xsl:choose>
				<xsl:when test="contains($sDate, 'M')">
					<xsl:value-of select="substring-before(substring-after($sDate, 'M'), 'D')"/>
				</xsl:when>
				<xsl:when test="contains($sDate, 'Y')">
					<xsl:value-of select="substring-before(substring-after($sDate, 'Y'), 'D')"/>
				</xsl:when>
				<xsl:otherwise>
					<xsl:value-of select="substring-before(substring-after($sDate, 'P'), 'D')"/>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:variable>
		<xsl:choose>
			<xsl:when test="string-length($sDay)=0">
				<xsl:value-of select="'0'"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="concat(substring-before(string($sDuration), 'P'), $sDay)"/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
	<xsl:template name="DurationToHour">
		<xsl:param name="sDuration"/>
		<xsl:variable name="sTime" select="substring-after(string($sDuration), 'T')"/>
		<xsl:variable name="sHour" select="substring-before($sTime, 'H')"/>
		<xsl:choose>
			<xsl:when test="string-length($sHour)=0">
				<xsl:value-of select="'0'"/>
			</xsl:when>
			<xsl:otherwise>
				<xsl:value-of select="concat(substring-before(string($sDuration), 'P'), $sHour)"/>
			</xsl:otherwise>
		</xsl:choose>
	</xsl:template>
</xsl:stylesheet>
