// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.20738
//    <NameSpace>TechnoLogica.RegiX.GraoNBDAdapter</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.RegiX.GraoNBDAdapter {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.23997")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/GRAO/NBD/PersonDataResponse")]
    [System.Xml.Serialization.XmlRootAttribute("PersonDataResponse", Namespace="http://egov.bg/RegiX/GRAO/NBD/PersonDataResponse", IsNullable=false)]
    public partial class PersonDataResponseType {
        
        private PersonNames personNamesField;
        
        private string aliasField;
        
        private PersonNames latinNamesField;
        
        private PersonNames foreignNamesField;
        
        private Gender genderField;
        
        private string eGNField;
        
        private System.DateTime birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private string placeBirthField;
        
        private Nationality nationalityField;
        
        private System.DateTime deathDateField;
        
        private bool deathDateFieldSpecified;
        
        /// <summary>
        /// PersonDataResponseType class constructor
        /// </summary>
        public PersonDataResponseType() {
            this.nationalityField = new Nationality();
            this.genderField = new Gender();
            this.foreignNamesField = new PersonNames();
            this.latinNamesField = new PersonNames();
            this.personNamesField = new PersonNames();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PersonNames PersonNames {
            get {
                return this.personNamesField;
            }
            set {
                this.personNamesField = value;
            }
        }
        
        /// <summary>
        /// Псевдоним
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Псевдоним")]
        public string Alias {
            get {
                return this.aliasField;
            }
            set {
                this.aliasField = value;
            }
        }
        
        /// <summary>
        /// Имена на латиница
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Имена на латиница")]
        public PersonNames LatinNames {
            get {
                return this.latinNamesField;
            }
            set {
                this.latinNamesField = value;
            }
        }
        
        /// <summary>
        /// Други известни имена в чужбина
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Други известни имена в чужбина")]
        public PersonNames ForeignNames {
            get {
                return this.foreignNamesField;
            }
            set {
                this.foreignNamesField = value;
            }
        }
        
        /// <summary>
        /// Пол
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DescriptionAttribute("Пол")]
        public Gender Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <summary>
        /// ЕГН
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DescriptionAttribute("ЕГН")]
        public string EGN {
            get {
                return this.eGNField;
            }
            set {
                this.eGNField = value;
            }
        }
        
        /// <summary>
        /// Дата на раждане
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        [System.ComponentModel.DescriptionAttribute("Дата на раждане")]
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BirthDateSpecified {
            get {
                return this.birthDateFieldSpecified;
            }
            set {
                this.birthDateFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Място на раждане
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        [System.ComponentModel.DescriptionAttribute("Място на раждане")]
        public string PlaceBirth {
            get {
                return this.placeBirthField;
            }
            set {
                this.placeBirthField = value;
            }
        }
        
        /// <summary>
        /// Гражданство
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        [System.ComponentModel.DescriptionAttribute("Гражданство")]
        public Nationality Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
            }
        }
        
        /// <summary>
        /// Дата на смърт
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=9)]
        [System.ComponentModel.DescriptionAttribute("Дата на смърт")]
        public System.DateTime DeathDate {
            get {
                return this.deathDateField;
            }
            set {
                this.deathDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeathDateSpecified {
            get {
                return this.deathDateFieldSpecified;
            }
            set {
                this.deathDateFieldSpecified = value;
            }
        }
    }
}
