// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.19205
//    <NameSpace>TechnoLogica.RegiX.MVRERChAdapter</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.RegiX.MVRERChAdapter {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17556")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse")]
    [System.Xml.Serialization.XmlRootAttribute("ForeignIdentityInfoResponse", Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse", IsNullable=false)]
    public partial class ForeignIdentityInfoResponseType {
        
        private ReturnInformation returnInformationsField;
        
        private string eGNField;
        
        private string lNChField;
        
        private PersonNames personNamesField;
        
        private string birthDateField;
        
        private BirthPlace birthPlaceField;
        
        private string genderNameField;
        
        private string genderNameLatinField;
        
        private List<Nationality> nationalityListField;
        
        private List<Status> statusesField;
        
        private AddressBG permanentAddressField;
        
        private AddressBG temporaryAddressField;
        
        private AddressAbroad permanentAddressAbroadField;
        
        private IdentityDocument identityDocumentField;
        
        private TravelDocument travelDocumentField;
        
        private double heightField;
        
        private bool heightFieldSpecified;
        
        private string eyesColorField;
        
        private string eyesColorLatinField;
        
        private byte[] pictureField;
        
        private byte[] identitySignatureField;
        
        /// <summary>
        /// ForeignIdentityInfoResponseType class constructor
        /// </summary>
        public ForeignIdentityInfoResponseType() {
            this.travelDocumentField = new TravelDocument();
            this.identityDocumentField = new IdentityDocument();
            this.permanentAddressAbroadField = new AddressAbroad();
            this.temporaryAddressField = new AddressBG();
            this.permanentAddressField = new AddressBG();
            this.statusesField = new List<Status>();
            this.nationalityListField = new List<Nationality>();
            this.birthPlaceField = new BirthPlace();
            this.personNamesField = new PersonNames();
            this.returnInformationsField = new ReturnInformation();
        }
        
        /// <summary>
        /// Информация на резултат
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Информация на резултат")]
        public ReturnInformation ReturnInformations {
            get {
                return this.returnInformationsField;
            }
            set {
                this.returnInformationsField = value;
            }
        }
        
        /// <summary>
        /// ЕГН
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("ЕГН")]
        public string EGN {
            get {
                return this.eGNField;
            }
            set {
                this.eGNField = value;
            }
        }
        
        /// <summary>
        /// ЛНЧ
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("ЛНЧ")]
        public string LNCh {
            get {
                return this.lNChField;
            }
            set {
                this.lNChField = value;
            }
        }
        
        /// <summary>
        /// Имена
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Имена")]
        public PersonNames PersonNames {
            get {
                return this.personNamesField;
            }
            set {
                this.personNamesField = value;
            }
        }
        
        /// <summary>
        /// Дата на раждане
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DescriptionAttribute("Дата на раждане")]
        public string BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <summary>
        /// Място на раждане
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DescriptionAttribute("Място на раждане")]
        public BirthPlace BirthPlace {
            get {
                return this.birthPlaceField;
            }
            set {
                this.birthPlaceField = value;
            }
        }
        
        /// <summary>
        /// Наименование на пол
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        [System.ComponentModel.DescriptionAttribute("Наименование на пол")]
        public string GenderName {
            get {
                return this.genderNameField;
            }
            set {
                this.genderNameField = value;
            }
        }
        
        /// <summary>
        /// Наименование на пол на латиница
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        [System.ComponentModel.DescriptionAttribute("Наименование на пол на латиница")]
        public string GenderNameLatin {
            get {
                return this.genderNameLatinField;
            }
            set {
                this.genderNameLatinField = value;
            }
        }
        
        /// <summary>
        /// Списък други гражданства
        /// </summary>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        [System.ComponentModel.DescriptionAttribute("Списък други гражданства")]
        public List<Nationality> NationalityList {
            get {
                return this.nationalityListField;
            }
            set {
                this.nationalityListField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public List<Status> Statuses {
            get {
                return this.statusesField;
            }
            set {
                this.statusesField = value;
            }
        }
        
        /// <summary>
        /// Постоянен адрес
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        [System.ComponentModel.DescriptionAttribute("Постоянен адрес")]
        public AddressBG PermanentAddress {
            get {
                return this.permanentAddressField;
            }
            set {
                this.permanentAddressField = value;
            }
        }
        
        /// <summary>
        /// Временен адрес
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        [System.ComponentModel.DescriptionAttribute("Временен адрес")]
        public AddressBG TemporaryAddress {
            get {
                return this.temporaryAddressField;
            }
            set {
                this.temporaryAddressField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public AddressAbroad PermanentAddressAbroad {
            get {
                return this.permanentAddressAbroadField;
            }
            set {
                this.permanentAddressAbroadField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public IdentityDocument IdentityDocument {
            get {
                return this.identityDocumentField;
            }
            set {
                this.identityDocumentField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public TravelDocument TravelDocument {
            get {
                return this.travelDocumentField;
            }
            set {
                this.travelDocumentField = value;
            }
        }
        
        /// <summary>
        /// Височина в см.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        [System.ComponentModel.DescriptionAttribute("Височина в см.")]
        public double Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Цвят на очите
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        [System.ComponentModel.DescriptionAttribute("Цвят на очите")]
        public string EyesColor {
            get {
                return this.eyesColorField;
            }
            set {
                this.eyesColorField = value;
            }
        }
        
        /// <summary>
        /// Цвят на очите на латиница
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        [System.ComponentModel.DescriptionAttribute("Цвят на очите на латиница")]
        public string EyesColorLatin {
            get {
                return this.eyesColorLatinField;
            }
            set {
                this.eyesColorLatinField = value;
            }
        }
        
        /// <summary>
        /// Снимка
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=18)]
        [System.ComponentModel.DescriptionAttribute("Снимка")]
        public byte[] Picture {
            get {
                return this.pictureField;
            }
            set {
                this.pictureField = value;
            }
        }
        
        /// <summary>
        /// Личен подпис
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=19)]
        [System.ComponentModel.DescriptionAttribute("Личен подпис")]
        public byte[] IdentitySignature {
            get {
                return this.identitySignatureField;
            }
            set {
                this.identitySignatureField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17556")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse", IsNullable=true)]
    public partial class ReturnInformation {
        
        private string returnCodeField;
        
        private string infoField;
        
        /// <summary>
        /// 0000-успешна операция;0100-няма данни отговарящи на условието.Други значения означават възникване на грешка - подлежат на допълнително уточняване.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("0000-успешна операция;0100-няма данни отговарящи на условието.Други значения озна" +
            "чават възникване на грешка - подлежат на допълнително уточняване.")]
        public string ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <summary>
        /// Описание на грешката
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Описание на грешката")]
        public string Info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17556")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse", IsNullable=true)]
    public partial class TravelDocument {
        
        private string documentTypeField;
        
        private string documentTypeLatinField;
        
        private string travelDocumentSeriesField;
        
        private string travelDocumentNumberField;
        
        private System.DateTime issueDateField;
        
        private bool issueDateFieldSpecified;
        
        private string issuePlaceField;
        
        private string issuePlaceLatinField;
        
        private string issuerNameField;
        
        private string issuerNameLatinField;
        
        private System.DateTime validDateField;
        
        private bool validDateFieldSpecified;
        
        /// <summary>
        /// Вид документ
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Вид документ")]
        public string DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <summary>
        /// Вид документ на латиница
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Вид документ на латиница")]
        public string DocumentTypeLatin {
            get {
                return this.documentTypeLatinField;
            }
            set {
                this.documentTypeLatinField = value;
            }
        }
        
        /// <summary>
        /// Серия
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Серия")]
        public string TravelDocumentSeries {
            get {
                return this.travelDocumentSeriesField;
            }
            set {
                this.travelDocumentSeriesField = value;
            }
        }
        
        /// <summary>
        /// Номер
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Номер")]
        public string TravelDocumentNumber {
            get {
                return this.travelDocumentNumberField;
            }
            set {
                this.travelDocumentNumberField = value;
            }
        }
        
        /// <summary>
        /// Дата на издаване
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DescriptionAttribute("Дата на издаване")]
        public System.DateTime IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssueDateSpecified {
            get {
                return this.issueDateFieldSpecified;
            }
            set {
                this.issueDateFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Място на издаване
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DescriptionAttribute("Място на издаване")]
        public string IssuePlace {
            get {
                return this.issuePlaceField;
            }
            set {
                this.issuePlaceField = value;
            }
        }
        
        /// <summary>
        /// Място на издаване на латиница
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        [System.ComponentModel.DescriptionAttribute("Място на издаване на латиница")]
        public string IssuePlaceLatin {
            get {
                return this.issuePlaceLatinField;
            }
            set {
                this.issuePlaceLatinField = value;
            }
        }
        
        /// <summary>
        /// Издаващ орган
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        [System.ComponentModel.DescriptionAttribute("Издаващ орган")]
        public string IssuerName {
            get {
                return this.issuerNameField;
            }
            set {
                this.issuerNameField = value;
            }
        }
        
        /// <summary>
        /// Издаващ орган на латиница
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        [System.ComponentModel.DescriptionAttribute("Издаващ орган на латиница")]
        public string IssuerNameLatin {
            get {
                return this.issuerNameLatinField;
            }
            set {
                this.issuerNameLatinField = value;
            }
        }
        
        /// <summary>
        /// Дата на валидност
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        [System.ComponentModel.DescriptionAttribute("Дата на валидност")]
        public System.DateTime ValidDate {
            get {
                return this.validDateField;
            }
            set {
                this.validDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidDateSpecified {
            get {
                return this.validDateFieldSpecified;
            }
            set {
                this.validDateFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17556")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse", IsNullable=true)]
    public partial class IdentityDocument {
        
        private string documentTypeField;
        
        private string documentTypeLatinField;
        
        private string identityDocumentNumberField;
        
        private System.DateTime issueDateField;
        
        private bool issueDateFieldSpecified;
        
        private string issuePlaceField;
        
        private string issuePlaceLatinField;
        
        private string issuerNameField;
        
        private string issuerNameLatinField;
        
        private System.DateTime validDateField;
        
        private bool validDateFieldSpecified;
        
        /// <summary>
        /// Вид документ за самоличност и пребиваване
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Вид документ за самоличност и пребиваване")]
        public string DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <summary>
        /// Вид документ за самоличност и пребиваване на латиница
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Вид документ за самоличност и пребиваване на латиница")]
        public string DocumentTypeLatin {
            get {
                return this.documentTypeLatinField;
            }
            set {
                this.documentTypeLatinField = value;
            }
        }
        
        /// <summary>
        /// Номер на документ за самоличност
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Номер на документ за самоличност")]
        public string IdentityDocumentNumber {
            get {
                return this.identityDocumentNumberField;
            }
            set {
                this.identityDocumentNumberField = value;
            }
        }
        
        /// <summary>
        /// Дата на издаване
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Дата на издаване")]
        public System.DateTime IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssueDateSpecified {
            get {
                return this.issueDateFieldSpecified;
            }
            set {
                this.issueDateFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Място на издаване
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DescriptionAttribute("Място на издаване")]
        public string IssuePlace {
            get {
                return this.issuePlaceField;
            }
            set {
                this.issuePlaceField = value;
            }
        }
        
        /// <summary>
        /// Място на издаване на латиница
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DescriptionAttribute("Място на издаване на латиница")]
        public string IssuePlaceLatin {
            get {
                return this.issuePlaceLatinField;
            }
            set {
                this.issuePlaceLatinField = value;
            }
        }
        
        /// <summary>
        /// Издаващ орган
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        [System.ComponentModel.DescriptionAttribute("Издаващ орган")]
        public string IssuerName {
            get {
                return this.issuerNameField;
            }
            set {
                this.issuerNameField = value;
            }
        }
        
        /// <summary>
        /// Издаващ орган на латиница
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        [System.ComponentModel.DescriptionAttribute("Издаващ орган на латиница")]
        public string IssuerNameLatin {
            get {
                return this.issuerNameLatinField;
            }
            set {
                this.issuerNameLatinField = value;
            }
        }
        
        /// <summary>
        /// Дата на валидност
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        [System.ComponentModel.DescriptionAttribute("Дата на валидност")]
        public System.DateTime ValidDate {
            get {
                return this.validDateField;
            }
            set {
                this.validDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidDateSpecified {
            get {
                return this.validDateFieldSpecified;
            }
            set {
                this.validDateFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17556")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse", IsNullable=true)]
    public partial class AddressAbroad {
        
        private string nationalityCodeField;
        
        private string nationalityNameField;
        
        private string nationalityNameLatinField;
        
        private string settlementNameField;
        
        private string streetField;
        
        /// <summary>
        /// Код на държава
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Код на държава")]
        public string NationalityCode {
            get {
                return this.nationalityCodeField;
            }
            set {
                this.nationalityCodeField = value;
            }
        }
        
        /// <summary>
        /// Наименование на държава
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Наименование на държава")]
        public string NationalityName {
            get {
                return this.nationalityNameField;
            }
            set {
                this.nationalityNameField = value;
            }
        }
        
        /// <summary>
        /// Наименование на държава на латиница
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Наименование на държава на латиница")]
        public string NationalityNameLatin {
            get {
                return this.nationalityNameLatinField;
            }
            set {
                this.nationalityNameLatinField = value;
            }
        }
        
        /// <summary>
        /// Наименование на населено място
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Наименование на населено място")]
        public string SettlementName {
            get {
                return this.settlementNameField;
            }
            set {
                this.settlementNameField = value;
            }
        }
        
        /// <summary>
        /// Данни за адресс
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DescriptionAttribute("Данни за адресс")]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17556")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse", IsNullable=true)]
    public partial class AddressBG {
        
        private string districtNameField;
        
        private string districtNameLatinField;
        
        private string municipalityNameField;
        
        private string municipalityNameLatinField;
        
        private string settlementCodeField;
        
        private string settlementNameField;
        
        private string settlementNameLatinField;
        
        private string locationCodeField;
        
        private string locationNameField;
        
        private string locationNameLatinField;
        
        private string buildingNumberField;
        
        private string entranceField;
        
        private string floorField;
        
        private string apartmentField;
        
        /// <summary>
        /// Наименование на област
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Наименование на област")]
        public string DistrictName {
            get {
                return this.districtNameField;
            }
            set {
                this.districtNameField = value;
            }
        }
        
        /// <summary>
        /// Наименование на област на латиница
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Наименование на област на латиница")]
        public string DistrictNameLatin {
            get {
                return this.districtNameLatinField;
            }
            set {
                this.districtNameLatinField = value;
            }
        }
        
        /// <summary>
        /// Наименование на община
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Наименование на община")]
        public string MunicipalityName {
            get {
                return this.municipalityNameField;
            }
            set {
                this.municipalityNameField = value;
            }
        }
        
        /// <summary>
        /// Наименование на община на латиница
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Наименование на община на латиница")]
        public string MunicipalityNameLatin {
            get {
                return this.municipalityNameLatinField;
            }
            set {
                this.municipalityNameLatinField = value;
            }
        }
        
        /// <summary>
        /// Код на населено място
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DescriptionAttribute("Код на населено място")]
        public string SettlementCode {
            get {
                return this.settlementCodeField;
            }
            set {
                this.settlementCodeField = value;
            }
        }
        
        /// <summary>
        /// Наименование на населено място
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DescriptionAttribute("Наименование на населено място")]
        public string SettlementName {
            get {
                return this.settlementNameField;
            }
            set {
                this.settlementNameField = value;
            }
        }
        
        /// <summary>
        /// Наименование на населено място на латиница
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        [System.ComponentModel.DescriptionAttribute("Наименование на населено място на латиница")]
        public string SettlementNameLatin {
            get {
                return this.settlementNameLatinField;
            }
            set {
                this.settlementNameLatinField = value;
            }
        }
        
        /// <summary>
        /// Код на локализационна единица (улица)
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        [System.ComponentModel.DescriptionAttribute("Код на локализационна единица (улица)")]
        public string LocationCode {
            get {
                return this.locationCodeField;
            }
            set {
                this.locationCodeField = value;
            }
        }
        
        /// <summary>
        /// Наименование на локализационна единица (улица)
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        [System.ComponentModel.DescriptionAttribute("Наименование на локализационна единица (улица)")]
        public string LocationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
            }
        }
        
        /// <summary>
        /// Наименование на локализационна единица (улица) на латиница
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        [System.ComponentModel.DescriptionAttribute("Наименование на локализационна единица (улица) на латиница")]
        public string LocationNameLatin {
            get {
                return this.locationNameLatinField;
            }
            set {
                this.locationNameLatinField = value;
            }
        }
        
        /// <summary>
        /// Номер
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        [System.ComponentModel.DescriptionAttribute("Номер")]
        public string BuildingNumber {
            get {
                return this.buildingNumberField;
            }
            set {
                this.buildingNumberField = value;
            }
        }
        
        /// <summary>
        /// Вход
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        [System.ComponentModel.DescriptionAttribute("Вход")]
        public string Entrance {
            get {
                return this.entranceField;
            }
            set {
                this.entranceField = value;
            }
        }
        
        /// <summary>
        /// Етаж
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        [System.ComponentModel.DescriptionAttribute("Етаж")]
        public string Floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
            }
        }
        
        /// <summary>
        /// Апартамент
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        [System.ComponentModel.DescriptionAttribute("Апартамент")]
        public string Apartment {
            get {
                return this.apartmentField;
            }
            set {
                this.apartmentField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17556")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse", IsNullable=true)]
    public partial class Status {
        
        private string statusNameField;
        
        private string statusNameLatinField;
        
        private System.DateTime dateFromField;
        
        private bool dateFromFieldSpecified;
        
        private System.DateTime dateToField;
        
        private bool dateToFieldSpecified;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusName {
            get {
                return this.statusNameField;
            }
            set {
                this.statusNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusNameLatin {
            get {
                return this.statusNameLatinField;
            }
            set {
                this.statusNameLatinField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime DateFrom {
            get {
                return this.dateFromField;
            }
            set {
                this.dateFromField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateFromSpecified {
            get {
                return this.dateFromFieldSpecified;
            }
            set {
                this.dateFromFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime DateTo {
            get {
                return this.dateToField;
            }
            set {
                this.dateToField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateToSpecified {
            get {
                return this.dateToFieldSpecified;
            }
            set {
                this.dateToFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17556")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse", IsNullable=true)]
    public partial class Nationality {
        
        private string nationalityCodeField;
        
        private string nationalityNameField;
        
        private string nationalityNameLatinField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NationalityCode {
            get {
                return this.nationalityCodeField;
            }
            set {
                this.nationalityCodeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NationalityName {
            get {
                return this.nationalityNameField;
            }
            set {
                this.nationalityNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NationalityNameLatin {
            get {
                return this.nationalityNameLatinField;
            }
            set {
                this.nationalityNameLatinField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17556")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse", IsNullable=true)]
    public partial class BirthPlace {
        
        private string countryCodeField;
        
        private string countryNameField;
        
        private string countryNameLatinField;
        
        private string territorialUnitNameField;
        
        private string districtNameField;
        
        private string municipalityNameField;
        
        /// <summary>
        /// Код на държава
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Код на държава")]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <summary>
        /// Наименование на държава
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Наименование на държава")]
        public string CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
            }
        }
        
        /// <summary>
        /// Наименование на държава на латиница
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Наименование на държава на латиница")]
        public string CountryNameLatin {
            get {
                return this.countryNameLatinField;
            }
            set {
                this.countryNameLatinField = value;
            }
        }
        
        /// <summary>
        /// Наименование на населено място
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Наименование на населено място")]
        public string TerritorialUnitName {
            get {
                return this.territorialUnitNameField;
            }
            set {
                this.territorialUnitNameField = value;
            }
        }
        
        /// <summary>
        /// Наименование на област
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DescriptionAttribute("Наименование на област")]
        public string DistrictName {
            get {
                return this.districtNameField;
            }
            set {
                this.districtNameField = value;
            }
        }
        
        /// <summary>
        /// Наименование на община
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DescriptionAttribute("Наименование на община")]
        public string MunicipalityName {
            get {
                return this.municipalityNameField;
            }
            set {
                this.municipalityNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17556")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse", IsNullable=true)]
    public partial class PersonNames {
        
        private string firstNameField;
        
        private string surnameField;
        
        private string familyNameField;
        
        private string firstNameLatinField;
        
        private string surnameLatinField;
        
        private string lastNameLatinField;
        
        /// <summary>
        /// Собствено име
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Собствено име")]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <summary>
        /// Бащино име
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Бащино име")]
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <summary>
        /// Фамилно име
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Фамилно име")]
        public string FamilyName {
            get {
                return this.familyNameField;
            }
            set {
                this.familyNameField = value;
            }
        }
        
        /// <summary>
        /// Собствено име, изписано на латиница
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Собствено име, изписано на латиница")]
        public string FirstNameLatin {
            get {
                return this.firstNameLatinField;
            }
            set {
                this.firstNameLatinField = value;
            }
        }
        
        /// <summary>
        /// Бащино име, изписано на латиница
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DescriptionAttribute("Бащино име, изписано на латиница")]
        public string SurnameLatin {
            get {
                return this.surnameLatinField;
            }
            set {
                this.surnameLatinField = value;
            }
        }
        
        /// <summary>
        /// Фамилно име, изписано на латиница
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DescriptionAttribute("Фамилно име, изписано на латиница")]
        public string LastNameLatin {
            get {
                return this.lastNameLatinField;
            }
            set {
                this.lastNameLatinField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17556")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse", IsNullable=true)]
    public partial class NationalityList {
        
        private List<Nationality> nationalityField;
        
        /// <summary>
        /// NationalityList class constructor
        /// </summary>
        public NationalityList() {
            this.nationalityField = new List<Nationality>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Nationality", Order=0)]
        public List<Nationality> Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17556")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse", IsNullable=true)]
    public partial class Statuses {
        
        private List<Status> statusField;
        
        /// <summary>
        /// Statuses class constructor
        /// </summary>
        public Statuses() {
            this.statusField = new List<Status>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Status", Order=0)]
        public List<Status> Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
}
