// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.23276
//    <NameSpace>mj_cais.bulletis</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MJ_CAIS.BulletinModel
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.23297")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://cs.mjs.bg/EISSServicesModel-v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("SendDataRequest", Namespace = "http://cs.mjs.bg/EISSServicesModel-v1.0", IsNullable = false)]
    public partial class SendDataRequestType
    {

        private BulletinsList bulletinsListField;

        private System.DateTime dateFromField;

        private System.DateTime dateToField;

        /// <summary>
        /// Списък с бюлетини
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        [System.ComponentModel.DescriptionAttribute("Списък с бюлетини")]
        public BulletinsList BulletinsList
        {
            get
            {
                return this.bulletinsListField;
            }
            set
            {
                this.bulletinsListField = value;
            }
        }

        /// <summary>
        /// От дата - начало на период в който са създадени бюлетините
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.ComponentModel.DescriptionAttribute("От дата - начало на период в който са създадени бюлетините")]
        public System.DateTime DateFrom
        {
            get
            {
                return this.dateFromField;
            }
            set
            {
                this.dateFromField = value;
            }
        }

        /// <summary>
        /// До дата - край на период, в който са създадени бюлетините
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        [System.ComponentModel.DescriptionAttribute("До дата - край на период, в който са създадени бюлетините")]
        public System.DateTime DateTo
        {
            get
            {
                return this.dateToField;
            }
            set
            {
                this.dateToField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.23297")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://cs.mjs.bg/EISSServicesModel-v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://cs.mjs.bg/EISSServicesModel-v1.0", IsNullable = true)]
    public partial class BulletinsList
    {

        private BulletinType[] bulletinField;

        [System.Xml.Serialization.XmlElementAttribute("Bulletin", Order = 0)]
        public BulletinType[] Bulletin
        {
            get
            {
                return this.bulletinField;
            }
            set
            {
                this.bulletinField = value;
            }
        }
    }
}
