// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.23276
//    <NameSpace>MJ_CAIS.IntegrationModel</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MJ_CAIS.IntegrationModel {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.23297")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cais.mjs.bg/CriminalRecordsReportResponse-v1.0")]
    [System.Xml.Serialization.XmlRootAttribute("CriminalRecordsReport", Namespace="http://cais.mjs.bg/CriminalRecordsReportResponse-v1.0", IsNullable=false)]
    public partial class CriminalRecordsReportType {
        
        private CriminalRecordsRequestType reportCriteriaField;
        
        private ReportResultType reportResultField;
        
        private System.DateTime reportDateField;
        
        /// <summary>
        /// Приложени критерии за търсене
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Приложени критерии за търсене")]
        public CriminalRecordsRequestType ReportCriteria {
            get {
                return this.reportCriteriaField;
            }
            set {
                this.reportCriteriaField = value;
            }
        }
        
        /// <summary>
        /// Резултат от справката
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Резултат от справката")]
        public ReportResultType ReportResult {
            get {
                return this.reportResultField;
            }
            set {
                this.reportResultField = value;
            }
        }
        
        /// <summary>
        /// Дата на справката
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Дата на справката")]
        public System.DateTime ReportDate {
            get {
                return this.reportDateField;
            }
            set {
                this.reportDateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.23297")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cais.mjs.bg/CriminalRecordsReportResponse-v1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://cais.mjs.bg/CriminalRecordsReportResponse-v1.0", IsNullable=true)]
    public partial class ReportResultType {
        
        private CriminalRecordsPersonDataType personDataField;
        
        private BulletinsList bulletinsListField;
        
        /// <summary>
        /// Данни за лицето
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Данни за лицето")]
        public CriminalRecordsPersonDataType PersonData {
            get {
                return this.personDataField;
            }
            set {
                this.personDataField = value;
            }
        }
        
        /// <summary>
        /// Списък с осъждания
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Списък с осъждания")]
        public BulletinsList BulletinsList {
            get {
                return this.bulletinsListField;
            }
            set {
                this.bulletinsListField = value;
            }
        }
    }
}
