<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2008 rel. 2 sp1 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:n1="http://egov.bg/RegiX/MVR/RCH//ForeignIdentityInfoResponse" xmlns:xdt="http://www.w3.org/2005/xpath-datatypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:altova="http://www.altova.com">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.0 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:decimal-format name="format1" grouping-separator=" " decimal-separator=","/>
	<xsl:template match="/">
		<html>
			<head>
				<title/>
			</head>
			<body>
				<xsl:for-each select="$XML">
					<xsl:for-each select="n1:ForeignIdentityInfoResponse">
						<h3 style="text-align:center; ">
							<span>
								<xsl:text>Министерство на вътрешните работи</xsl:text>
							</span>
							<br/>
							<span>
								<xsl:text>Единен регистър на чужденците</xsl:text>
							</span>
						</h3>
						<h2 style="text-align:center; ">
							<span>
								<xsl:text>Справка за физическо лице – чужденец</xsl:text>
							</span>
						</h2>
						<xsl:choose>
							<xsl:when test="n1:ReturnInformations/n1:ReturnCode =&apos;0000&apos;">
								<xsl:choose>
									<xsl:when test="string-length( n1:EGN ) +string-length( n1:LNCh  ) + string-length( n1:PersonNames )+string-length(  n1:BirthDate  )+string-length( n1:BirthPlace  )+string-length(  n1:GenderName  )+ string-length( n1:GenderNameLatin  )+string-length( n1:NationalityList  )+string-length(  n1:Statuses )+string-length(  n1:PermanentAddress  )+string-length(  n1:TemporaryAddress  )+string-length(  n1:PermanentAddressAbroad  )+string-length(  n1:IdentityDocument  )+string-length(  n1:TravelDocument  )+string-length(  n1:Height  )+string-length(  n1:EyesColor  )+string-length(  n1:EyesColorLatin )&gt;0">
										<div>
											<span style="font-style:italic; font-weight:bold; ">
												<xsl:text>Лични данни</xsl:text>
											</span>
										</div>
										<xsl:for-each select="n1:EGN">
											<xsl:if test="string-length(. )&gt;0">
												<table border="0" width="100%">
													<tbody>
														<tr valign="top">
															<th align="left" width="250px">
																<span style="font-style:italic; font-weight:normal; ">
																	<xsl:text>ЕГН</xsl:text>
																</span>
															</th>
															<td>
																<xsl:apply-templates/>
															</td>
														</tr>
													</tbody>
												</table>
											</xsl:if>
										</xsl:for-each>
										<xsl:for-each select="n1:LNCh">
											<xsl:if test="string-length(. )&gt;0">
												<table border="0" width="100%">
													<tbody>
														<tr valign="top">
															<th align="left" width="250px">
																<span style="font-style:italic; font-weight:normal; ">
																	<xsl:text>ЛНЧ</xsl:text>
																</span>
															</th>
															<td>
																<xsl:apply-templates/>
															</td>
														</tr>
													</tbody>
												</table>
											</xsl:if>
										</xsl:for-each>
										<xsl:for-each select="n1:PersonNames">
											<xsl:if test="string-length( . )&gt;0">
												<table border="0" width="100%">
													<tbody>
														<tr valign="top">
															<th align="left" width="250px">
																<span style="font-style:italic; font-weight:normal; ">
																	<xsl:text>Имена</xsl:text>
																</span>
															</th>
															<td>
																<xsl:for-each select="n1:FirstName">
																	<xsl:apply-templates/>
																</xsl:for-each>
																<xsl:for-each select="n1:Surname">
																	<span>
																		<xsl:text>&#160;</xsl:text>
																	</span>
																	<xsl:apply-templates/>
																</xsl:for-each>
																<xsl:for-each select="n1:FamilyName">
																	<span>
																		<xsl:text>&#160;</xsl:text>
																	</span>
																	<xsl:apply-templates/>
																</xsl:for-each>
															</td>
														</tr>
														<tr valign="top">
															<th align="left" width="250px">
																<span style="font-style:italic; font-weight:normal; ">
																	<xsl:text>Имена(лат.)</xsl:text>
																</span>
															</th>
															<td>
																<xsl:for-each select="n1:FirstNameLatin">
																	<xsl:apply-templates/>
																</xsl:for-each>
																<xsl:for-each select="n1:SurnameLatin">
																	<span>
																		<xsl:text>&#160;</xsl:text>
																	</span>
																	<xsl:apply-templates/>
																</xsl:for-each>
																<xsl:for-each select="n1:LastNameLatin">
																	<span>
																		<xsl:text>&#160;</xsl:text>
																	</span>
																	<xsl:apply-templates/>
																</xsl:for-each>
															</td>
														</tr>
													</tbody>
												</table>
											</xsl:if>
										</xsl:for-each>
										<xsl:for-each select="n1:GenderName">
											<xsl:if test="string-length(. )&gt;0">
												<table border="0" width="100%">
													<tbody>
														<tr valign="top">
															<th align="left" width="250px">
																<span style="font-style:italic; font-weight:normal; ">
																	<xsl:text>Пол</xsl:text>
																</span>
															</th>
															<td>
																<xsl:apply-templates/>
															</td>
														</tr>
													</tbody>
												</table>
											</xsl:if>
										</xsl:for-each>
										<xsl:for-each select="n1:GenderNameLatin">
											<xsl:if test="string-length(. )&gt;0">
												<table border="0" width="100%">
													<tbody>
														<tr valign="top">
															<th align="left" width="250px">
																<span style="font-style:italic; font-weight:normal; ">
																	<xsl:text>Пол(лат.)</xsl:text>
																</span>
															</th>
															<td>
																<xsl:apply-templates/>
															</td>
														</tr>
													</tbody>
												</table>
											</xsl:if>
										</xsl:for-each>
										<xsl:for-each select="n1:Height">
											<xsl:if test="string-length(. )&gt;0">
												<table border="0" width="100%">
													<tbody>
														<tr valign="top">
															<th align="left" width="250px">
																<span style="font-style:italic; font-weight:normal; ">
																	<xsl:text>Височина</xsl:text>
																</span>
															</th>
															<td>
																<xsl:apply-templates/>
															</td>
														</tr>
													</tbody>
												</table>
											</xsl:if>
										</xsl:for-each>
										<xsl:for-each select="n1:EyesColor">
											<xsl:if test="string-length(. )&gt;0">
												<table border="0" width="100%">
													<tbody>
														<tr valign="top">
															<th align="left" width="250px">
																<span style="font-style:italic; font-weight:normal; ">
																	<xsl:text>Цвят на очите</xsl:text>
																</span>
															</th>
															<td>
																<xsl:apply-templates/>
															</td>
														</tr>
													</tbody>
												</table>
											</xsl:if>
										</xsl:for-each>
										<xsl:for-each select="n1:EyesColorLatin">
											<xsl:if test="string-length(. )&gt;0">
												<table border="0" width="100%">
													<tbody>
														<tr valign="top">
															<th align="left" width="250px">
																<span style="font-style:italic; font-weight:normal; ">
																	<xsl:text>Цвят на очите(лат.)</xsl:text>
																</span>
															</th>
															<td>
																<xsl:apply-templates/>
															</td>
														</tr>
													</tbody>
												</table>
											</xsl:if>
										</xsl:for-each>
										<xsl:for-each select="n1:BirthDate">
											<xsl:if test="string-length(. )&gt;0">
												<table border="0" width="100%">
													<tbody>
														<tr valign="top">
															<th align="left" width="250px">
																<span style="font-style:italic; font-weight:normal; ">
																	<xsl:text>Дата на раждане</xsl:text>
																</span>
															</th>
															<td>
																<span>
																	<xsl:value-of select="substring( . , 1 , 2 )"/>
																</span>
																<span>
																	<xsl:text>.</xsl:text>
																</span>
																<span>
																	<xsl:value-of select="substring( . , 4 , 2 )"/>
																</span>
																<span>
																	<xsl:text>.</xsl:text>
																</span>
																<span>
																	<xsl:value-of select="substring( . , 7 , 4 )"/>
																</span>
																<span>
																	<xsl:text> г.</xsl:text>
																</span>
															</td>
														</tr>
													</tbody>
												</table>
											</xsl:if>
										</xsl:for-each>
										<xsl:for-each select="n1:DeathDate">
											<xsl:if test="string-length(  . ) &gt;0">
												<table border="0" width="100%">
													<tbody>
														<tr>
															<td width="251">
																<span style="font-style:italic; ">
																	<xsl:text>Дата на смърт</xsl:text>
																</span>
															</td>
															<td>
																<span>
																	<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																	<xsl:text>.</xsl:text>
																	<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																	<xsl:text>.</xsl:text>
																	<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																</span>
																<span>
																	<xsl:text> г.</xsl:text>
																</span>
															</td>
														</tr>
													</tbody>
												</table>
											</xsl:if>
										</xsl:for-each>
										<br/>
										<xsl:if test="string-length( n1:BirthPlace )&gt;0">
											<div>
												<span style="font-style:italic; font-weight:bold; ">
													<xsl:text>Месторождение</xsl:text>
												</span>
											</div>
											<xsl:for-each select="n1:BirthPlace">
												<xsl:for-each select="n1:CountryName">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Държава</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:CountryNameLatin">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Държава(лат.)</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:DistrictName">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Област</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:MunicipalityName">
													<table border="0" width="100%">
														<tbody>
															<tr valign="top">
																<th align="left" width="250px">
																	<span style="font-style:italic; font-weight:normal; ">
																		<xsl:text>Община</xsl:text>
																	</span>
																</th>
																<td>
																	<xsl:apply-templates/>
																</td>
															</tr>
														</tbody>
													</table>
												</xsl:for-each>
												<xsl:for-each select="n1:TerritorialUnitName">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Населено място</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:if>
										<xsl:for-each select="n1:IdentityDocument">
											<xsl:if test="string-length(. )&gt;0">
												<div>
													<span style="font-style:italic; font-weight:bold; ">
														<xsl:text>Данни за документ за самоличност</xsl:text>
													</span>
												</div>
												<xsl:for-each select="n1:DocumentType">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Тип документ</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:DocumentTypeLatin">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Тип документ(лат.)</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:IdentityDocumentNumber">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Номер на документ за самоличност</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:IssueDate">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Дата на издаване</xsl:text>
																		</span>
																	</th>
																	<td>
																		<span>
																			<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																			<xsl:text>.</xsl:text>
																			<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																			<xsl:text>.</xsl:text>
																			<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																		</span>
																		<span>
																			<xsl:text> г.</xsl:text>
																		</span>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:IssuePlace">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Място на издаване</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:IssuePlaceLatin">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Място на издаване(лат.)</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:IssuerName">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Издаден от</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:IssuerNameLatin">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Издаден от(лат.)</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:ValidDate">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Валиден до</xsl:text>
																		</span>
																	</th>
																	<td>
																		<span>
																			<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																			<xsl:text>.</xsl:text>
																			<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																			<xsl:text>.</xsl:text>
																			<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																		</span>
																		<span>
																			<xsl:text> г.</xsl:text>
																		</span>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:StatusDate">
													<xsl:if test="string-length(  .  ) &gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr>
																	<td width="251">
																		<span style="font-style:italic; ">
																			<xsl:text>Дата на актуален статус</xsl:text>
																		</span>
																	</td>
																	<td>
																		<span>
																			<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																			<xsl:text>.</xsl:text>
																			<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																			<xsl:text>.</xsl:text>
																			<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																		</span>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:StatusReasonCyrillic">
													<br/>
													<xsl:if test="string-length( . ) &gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr>
																	<td width="256">
																		<span style="font-style:italic; ">
																			<xsl:text>Причина за актуален статус - текст на кирилица</xsl:text>
																		</span>
																	</td>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
													<br/>
												</xsl:for-each>
												<xsl:for-each select="n1:RPTypeOfPermit">
													<xsl:if test="string-length(  .  ) &gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr>
																	<td width="257">
																		<span style="font-style:italic; ">
																			<xsl:text>Тип пребиваване в док. Разрешение за пребиваване</xsl:text>
																		</span>
																	</td>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:RPRemarks">
													<xsl:if test="string-length(  .  ) &gt;0">
														<table style="border-collapse:collapse; " border="1" cellpadding="5px">
															<thead>
																<tr>
																	<th>
																		<span style="font-style:italic; ">
																			<xsl:text>Забележки в док. Разрешение за преб.</xsl:text>
																		</span>
																	</th>
																</tr>
															</thead>
															<tbody>
																<tr>
																	<td>
																		<xsl:for-each select="n1:RPRemark">
																			<xsl:apply-templates/>
																		</xsl:for-each>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
											</xsl:if>
										</xsl:for-each>
										<xsl:for-each select="n1:TravelDocument">
											<xsl:if test="string-length(. )&gt;0">
												<div>
													<span style="font-style:italic; font-weight:bold; ">
														<xsl:text>Документ за задгранично пътуване</xsl:text>
													</span>
												</div>
												<xsl:for-each select="n1:DocumentType">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Тип документ</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:DocumentTypeLatin">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Тип документ(лат.)</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:TravelDocumentSeries">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Серия на документ </xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:TravelDocumentNumber">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Номер на документ</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:IssueDate">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Дата на издаване</xsl:text>
																		</span>
																	</th>
																	<td>
																		<span>
																			<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																			<xsl:text>.</xsl:text>
																			<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																			<xsl:text>.</xsl:text>
																			<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																		</span>
																		<span>
																			<xsl:text> г.</xsl:text>
																		</span>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:IssuePlace">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Място на издаване</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:IssuePlaceLatin">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Място на издаване(лат.)</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:IssuerName">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Издаден от</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:IssuerNameLatin">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Издаден от(лат.)</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:ValidDate">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Валиден до</xsl:text>
																		</span>
																	</th>
																	<td>
																		<span>
																			<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																			<xsl:text>.</xsl:text>
																			<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																			<xsl:text>.</xsl:text>
																			<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																		</span>
																		<span>
																			<xsl:text> г.</xsl:text>
																		</span>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:StatusDate">
													<xsl:if test="string-length(  .  ) &gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr>
																	<td width="251">
																		<span style="font-style:italic; ">
																			<xsl:text>Дата на актуален статус</xsl:text>
																		</span>
																	</td>
																	<td>
																		<span>
																			<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																			<xsl:text>.</xsl:text>
																			<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																			<xsl:text>.</xsl:text>
																			<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																		</span>
																		<span>
																			<xsl:text> г.</xsl:text>
																		</span>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:StatusReasonCyrillic">
													<xsl:if test="string-length( . ) &gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr>
																	<td width="253">
																		<span style="font-style:italic; ">
																			<xsl:text>Причина за актуален статус</xsl:text>
																		</span>
																	</td>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
											</xsl:if>
										</xsl:for-each>
										<xsl:for-each select="n1:NationalityList">
											<xsl:if test="string-length(. )&gt;0">
												<div>
													<span style="font-style:italic; font-weight:bold; ">
														<xsl:text>Националност</xsl:text>
													</span>
												</div>
												<table style="border-collapse:collapse; " border="1" cellpadding="5px">
													<thead>
														<tr>
															<th>
																<span style="font-style:italic; font-weight:normal; ">
																	<xsl:text>Код</xsl:text>
																</span>
															</th>
															<th>
																<span style="font-style:italic; font-weight:normal; ">
																	<xsl:text>Държава</xsl:text>
																</span>
															</th>
															<th>
																<span style="font-style:italic; font-weight:normal; ">
																	<xsl:text>Държава(лат.)</xsl:text>
																</span>
															</th>
														</tr>
													</thead>
													<tbody>
														<xsl:for-each select="n1:Nationality">
															<tr>
																<td>
																	<xsl:for-each select="n1:NationalityCode">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</td>
																<td>
																	<xsl:for-each select="n1:NationalityName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</td>
																<td>
																	<xsl:for-each select="n1:NationalityNameLatin">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</td>
															</tr>
														</xsl:for-each>
													</tbody>
												</table>
											</xsl:if>
										</xsl:for-each>
										<xsl:if test="string-length(n1:PermanentAddress )&gt;0">
											<xsl:for-each select="n1:PermanentAddress">
												<div>
													<span style="font-style:italic; font-weight:bold; ">
														<xsl:text>Постоянен адрес</xsl:text>
													</span>
												</div>
												<xsl:for-each select="n1:DistrictName">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Област</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:DistrictNameLatin">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" cellpadding="3" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Област(лат.)</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:MunicipalityName">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Община</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:MunicipalityNameLatin">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Община(лат.)</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:SettlementName">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Населено място</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:SettlementCode">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Код на населено място</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:SettlementNameLatin">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Населено място(лат.)</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<table border="0" width="100%">
													<tbody>
														<tr valign="top">
															<th align="left" width="250px">
																<span style="font-style:italic; font-weight:normal; ">
																	<xsl:text>Адрес</xsl:text>
																</span>
															</th>
															<td>
																<xsl:for-each select="n1:LocationName">
																	<xsl:apply-templates/>
																</xsl:for-each>
																<xsl:for-each select="n1:LocationNameLatin">
																	<span>
																		<xsl:text>(</xsl:text>
																	</span>
																	<xsl:apply-templates/>
																	<span>
																		<xsl:text>)</xsl:text>
																	</span>
																</xsl:for-each>
																<xsl:for-each select="n1:BuildingNumber">
																	<span>
																		<xsl:text>, номер </xsl:text>
																	</span>
																	<xsl:apply-templates/>
																</xsl:for-each>
																<xsl:for-each select="n1:Entrance">
																	<span>
																		<xsl:text>, вх. </xsl:text>
																	</span>
																	<xsl:apply-templates/>
																</xsl:for-each>
																<xsl:for-each select="n1:Floor">
																	<span>
																		<xsl:text>, ет. </xsl:text>
																	</span>
																	<xsl:apply-templates/>
																</xsl:for-each>
																<xsl:for-each select="n1:Apartment">
																	<span>
																		<xsl:text>, ап. </xsl:text>
																	</span>
																	<xsl:apply-templates/>
																</xsl:for-each>
															</td>
														</tr>
													</tbody>
												</table>
											</xsl:for-each>
										</xsl:if>
										<xsl:if test="string-length( n1:TemporaryAddress  )&gt;0">
											<xsl:for-each select="n1:TemporaryAddress">
												<div>
													<span style="font-style:italic; font-weight:bold; ">
														<xsl:text>Настоящ адрес</xsl:text>
													</span>
												</div>
												<xsl:for-each select="n1:DistrictName">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Област</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:DistrictNameLatin">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" cellpadding="3" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Област(лат.)</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:MunicipalityName">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Община</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:MunicipalityNameLatin">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Община(лат.)</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:SettlementName">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Населено място</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:SettlementCode">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Код на населено място</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<xsl:for-each select="n1:SettlementNameLatin">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="250px">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Населено място(лат.)</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<table border="0" width="100%">
													<tbody>
														<tr valign="top">
															<th align="left" width="250px">
																<span style="font-style:italic; font-weight:normal; ">
																	<xsl:text>Адрес</xsl:text>
																</span>
															</th>
															<td>
																<xsl:for-each select="n1:LocationName">
																	<xsl:apply-templates/>
																</xsl:for-each>
																<xsl:for-each select="n1:LocationNameLatin">
																	<span>
																		<xsl:text>(</xsl:text>
																	</span>
																	<xsl:apply-templates/>
																	<span>
																		<xsl:text>)</xsl:text>
																	</span>
																</xsl:for-each>
																<xsl:for-each select="n1:BuildingNumber">
																	<span>
																		<xsl:text>&#160;</xsl:text>
																	</span>
																	<xsl:apply-templates/>
																</xsl:for-each>
																<xsl:for-each select="n1:Entrance">
																	<span>
																		<xsl:text> вх. </xsl:text>
																	</span>
																	<xsl:apply-templates/>
																</xsl:for-each>
																<xsl:for-each select="n1:Floor">
																	<span>
																		<xsl:text> ет. </xsl:text>
																	</span>
																	<xsl:apply-templates/>
																</xsl:for-each>
																<xsl:for-each select="n1:Apartment">
																	<span>
																		<xsl:text> ап. </xsl:text>
																	</span>
																	<xsl:apply-templates/>
																</xsl:for-each>
															</td>
														</tr>
													</tbody>
												</table>
											</xsl:for-each>
										</xsl:if>
										<xsl:if test="string-length( n1:PermanentAddressAbroad  )&gt;0">
											<xsl:for-each select="n1:PermanentAddressAbroad">
												<br/>
												<div>
													<span style="font-style:italic; font-weight:bold; ">
														<xsl:text>Постоянен адрес в чужбина</xsl:text>
													</span>
												</div>
												<xsl:for-each select="n1:NationalityCode">
													<xsl:if test="count( . )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr>
																	<td width="264">
																		<span style="font-style:italic; ">
																			<xsl:text>Код на държава</xsl:text>
																		</span>
																	</td>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
													<br/>
												</xsl:for-each>
												<br/>
												<xsl:for-each select="n1:NationalityName">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr>
																	<td width="261">
																		<span style="font-style:italic; ">
																			<xsl:text>Наименование на държава</xsl:text>
																		</span>
																	</td>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<br/>
												<xsl:for-each select="n1:NationalityNameLatin">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr>
																	<td width="268">
																		<span style="font-style:italic; ">
																			<xsl:text>Наименование на държава на латиница</xsl:text>
																		</span>
																	</td>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<br/>
												<xsl:for-each select="n1:SettlementName">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr valign="top">
																	<th align="left" width="260">
																		<span style="font-style:italic; font-weight:normal; ">
																			<xsl:text>Населено място</xsl:text>
																		</span>
																	</th>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<br/>
												<xsl:for-each select="n1:Street">
													<xsl:if test="string-length(. )&gt;0">
														<table border="0" width="100%">
															<tbody>
																<tr>
																	<td width="258">
																		<span style="font-style:italic; ">
																			<xsl:text>Данни за адрес</xsl:text>
																		</span>
																	</td>
																	<td>
																		<xsl:apply-templates/>
																	</td>
																</tr>
															</tbody>
														</table>
													</xsl:if>
												</xsl:for-each>
												<br/>
											</xsl:for-each>
										</xsl:if>
										<xsl:for-each select="n1:Employer">
											<xsl:if test="string-length(  .  ) &gt;0">
												<table border="0" width="100%">
													<tbody>
														<tr>
															<td width="262">
																<span style="font-style:italic; ">
																	<xsl:text>Работодател</xsl:text>
																</span>
															</td>
															<td>
																<xsl:apply-templates/>
															</td>
														</tr>
													</tbody>
												</table>
											</xsl:if>
										</xsl:for-each>
										<xsl:for-each select="n1:Position">
											<xsl:if test="string-length( . )&gt;0">
												<table border="0" width="100%">
													<tbody>
														<tr>
															<td width="260">
																<span style="font-style:italic; ">
																	<xsl:text>Длъжност</xsl:text>
																</span>
															</td>
															<td>
																<xsl:apply-templates/>
															</td>
														</tr>
													</tbody>
												</table>
											</xsl:if>
										</xsl:for-each>
										<xsl:for-each select="n1:PositionLatin">
											<xsl:if test="string-length(  .  ) &gt;0">
												<table border="0" width="100%">
													<tbody>
														<tr>
															<td width="261">
																<span style="font-style:italic; ">
																	<xsl:text>Длъжност(лат.)</xsl:text>
																</span>
															</td>
															<td>
																<xsl:apply-templates/>
															</td>
														</tr>
													</tbody>
												</table>
											</xsl:if>
										</xsl:for-each>
										<br/>
										<br/>
										<br/>
										<xsl:for-each select="n1:Statuses">
											<xsl:if test="string-length(. )&gt;0">
												<div>
													<span style="font-style:italic; font-weight:bold; ">
														<xsl:text>Статус на пребиваване</xsl:text>
													</span>
												</div>
												<table style="border-collapse:collapse; " border="1" cellpadding="5px">
													<thead>
														<tr>
															<th>
																<span style="font-style:italic; font-weight:normal; ">
																	<xsl:text>Статус</xsl:text>
																</span>
															</th>
															<th>
																<span style="font-style:italic; font-weight:normal; ">
																	<xsl:text>Статус(лат.)</xsl:text>
																</span>
															</th>
															<th>
																<span style="font-style:italic; font-weight:normal; ">
																	<xsl:text>Валиден от</xsl:text>
																</span>
															</th>
															<th>
																<span style="font-style:italic; font-weight:normal; ">
																	<xsl:text>Валиден до</xsl:text>
																</span>
															</th>
														</tr>
													</thead>
													<tbody>
														<xsl:for-each select="n1:Status">
															<tr>
																<td>
																	<xsl:for-each select="n1:StatusName">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</td>
																<td>
																	<xsl:for-each select="n1:StatusNameLatin">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</td>
																<td>
																	<xsl:for-each select="n1:DateFrom">
																		<span>
																			<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																			<xsl:text>.</xsl:text>
																			<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																			<xsl:text>.</xsl:text>
																			<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																		</span>
																		<span>
																			<xsl:text> г.</xsl:text>
																		</span>
																	</xsl:for-each>
																</td>
																<td>
																	<xsl:for-each select="n1:DateTo">
																		<span>
																			<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																			<xsl:text>.</xsl:text>
																			<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																			<xsl:text>.</xsl:text>
																			<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																		</span>
																		<span>
																			<xsl:text> г.</xsl:text>
																		</span>
																	</xsl:for-each>
																</td>
															</tr>
														</xsl:for-each>
													</tbody>
												</table>
											</xsl:if>
											<br/>
											<xsl:for-each select="n1:StatusLawReason">
												<div>
													<span style="font-weight:bold; ">
														<xsl:text>Статус на правното основание</xsl:text>
													</span>
												</div>
												<xsl:if test="string-length(   n1:Status  )&gt;0">
													<table border="0" width="100%">
														<tbody>
															<tr>
																<td width="263">
																	<span style="font-style:italic; ">
																		<xsl:text>Статус на правното основание</xsl:text>
																	</span>
																</td>
																<td>
																	<xsl:for-each select="n1:Status">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</td>
															</tr>
														</tbody>
													</table>
												</xsl:if>
												<xsl:if test="string-length(  n1:StatusLatin  ) &gt;0">
													<table border="0" width="100%">
														<tbody>
															<tr>
																<td width="263">
																	<span style="font-style:italic; ">
																		<xsl:text>Статус на правното основание(лат)</xsl:text>
																	</span>
																</td>
																<td>
																	<xsl:for-each select="n1:StatusLatin">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</td>
															</tr>
														</tbody>
													</table>
												</xsl:if>
												<xsl:if test="string-length(  n1:Code  ) &gt;0">
													<table border="0" width="100%">
														<tbody>
															<tr>
																<td width="266">
																	<span style="font-style:italic; ">
																		<xsl:text>Код</xsl:text>
																	</span>
																</td>
																<td>
																	<xsl:for-each select="n1:Code">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</td>
															</tr>
														</tbody>
													</table>
												</xsl:if>
												<br/>
											</xsl:for-each>
											<xsl:for-each select="n1:StatusDocument">
												<br/>
												<div>
													<span style="font-weight:bold; ">
														<xsl:text>Документ за предоставянее/ отказ/ отнемане на статут</xsl:text>
													</span>
												</div>
												<xsl:if test="string-length(  n1:DocumentType ) &gt;0">
													<table border="0" width="100%">
														<tbody>
															<tr>
																<td width="265">
																	<span style="font-style:italic; ">
																		<xsl:text>Вид на документ</xsl:text>
																	</span>
																</td>
																<td>
																	<xsl:for-each select="n1:DocumentType">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</td>
															</tr>
														</tbody>
													</table>
												</xsl:if>
												<xsl:if test="string-length(  n1:DocumentTypeLatin  ) &gt;0">
													<table border="0" width="100%">
														<tbody>
															<tr>
																<td width="265">
																	<span style="font-style:italic; ">
																		<xsl:text>Вид на документ(лат)</xsl:text>
																	</span>
																</td>
																<td>
																	<xsl:for-each select="n1:DocumentTypeLatin">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</td>
															</tr>
														</tbody>
													</table>
												</xsl:if>
												<xsl:if test="string-length( n1:DocumentNumber ) &gt; 0">
													<table border="0" width="100%">
														<tbody>
															<tr>
																<td width="265">
																	<span style="font-style:italic; ">
																		<xsl:text>Статус на правното основание</xsl:text>
																	</span>
																</td>
																<td>
																	<xsl:for-each select="n1:DocumentNumber">
																		<xsl:apply-templates/>
																	</xsl:for-each>
																</td>
															</tr>
														</tbody>
													</table>
												</xsl:if>
												<xsl:if test="string-length(  n1:StatusDocumentDate  ) &gt;0">
													<table border="0" width="100%">
														<tbody>
															<tr>
																<td width="268">
																	<span style="font-style:italic; ">
																		<xsl:text>Дата на документ за статут</xsl:text>
																	</span>
																</td>
																<td>
																	<xsl:for-each select="n1:StatusDocumentDate">
																		<span>
																			<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																			<xsl:text>.</xsl:text>
																			<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																			<xsl:text>.</xsl:text>
																			<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
																		</span>
																		<span>
																			<xsl:text> г.</xsl:text>
																		</span>
																	</xsl:for-each>
																</td>
															</tr>
														</tbody>
													</table>
												</xsl:if>
											</xsl:for-each>
											<br/>
											<xsl:for-each select="n1:Category">
												<br/>
												<div>
													<span style="font-weight:bold; ">
														<xsl:text>Категории</xsl:text>
													</span>
												</div>
												<table style="border-collapse:collapse; " border="1" cellpadding="5px">
													<thead>
														<tr>
															<th>
																<span style="font-style:italic; ">
																	<xsl:text>Код</xsl:text>
																</span>
															</th>
															<th>
																<span>
																	<xsl:text>Категория(лат.)</xsl:text>
																</span>
															</th>
															<th>
																<span>
																	<xsl:text>Категория</xsl:text>
																</span>
															</th>
														</tr>
													</thead>
													<tbody>
														<tr>
															<td>
																<xsl:for-each select="n1:Code">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</td>
															<td>
																<xsl:for-each select="n1:CategoryLatin">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</td>
															<td>
																<xsl:for-each select="n1:CategoryCyrillic">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</td>
														</tr>
													</tbody>
												</table>
											</xsl:for-each>
										</xsl:for-each>
										<br/>
										<xsl:for-each select="n1:Picture">
											<div>
												<span style="font-style:italic; font-weight:bold; ">
													<xsl:text>Снимка</xsl:text>
												</span>
											</div>
											<img>
												<xsl:attribute name="src">
													<xsl:if test="substring(string(concat(&quot;data:image/png;base64,&quot;, string(.))), 2, 1) = ':'">
														<xsl:text>file:///</xsl:text>
													</xsl:if>
													<xsl:value-of select="translate(string(concat(&quot;data:image/png;base64,&quot;, string(.))), '&#x5c;', '/')"/>
												</xsl:attribute>
												<xsl:attribute name="alt"/>
											</img>
										</xsl:for-each>
										<xsl:for-each select="n1:IdentitySignature">
											<div>
												<span style="font-style:italic; font-weight:bold; ">
													<xsl:text>Личен подпис</xsl:text>
												</span>
											</div>
											<img>
												<xsl:attribute name="src">
													<xsl:if test="substring(string(concat(&quot;data:image/png;base64,&quot;, string(.))), 2, 1) = ':'">
														<xsl:text>file:///</xsl:text>
													</xsl:if>
													<xsl:value-of select="translate(string(concat(&quot;data:image/png;base64,&quot;, string(.))), '&#x5c;', '/')"/>
												</xsl:attribute>
												<xsl:attribute name="alt"/>
											</img>
										</xsl:for-each>
									</xsl:when>
									<xsl:otherwise>
										<span>
											<xsl:text>Не са намерени данни в реиистъра за подадените входни параметри.</xsl:text>
										</span>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:when>
							<xsl:otherwise>
								<xsl:for-each select="n1:ReturnInformations">
									<div>
										<span style="font-style:italic; font-weight:bold; ">
											<xsl:text>Възникна грешка при търсене на данните в регистъра</xsl:text>
										</span>
									</div>
									<xsl:for-each select="n1:ReturnCode">
										<table border="0" width="100%">
											<tbody>
												<tr valign="top">
													<th align="left" width="250px">
														<span style="font-style:italic; font-weight:normal; ">
															<xsl:text>Код на грешка</xsl:text>
														</span>
													</th>
													<td>
														<xsl:apply-templates/>
													</td>
												</tr>
											</tbody>
										</table>
									</xsl:for-each>
									<xsl:for-each select="n1:Info">
										<table border="0" width="100%">
											<tbody>
												<tr valign="top">
													<th align="left" width="250px">
														<span style="font-style:italic; font-weight:normal; ">
															<xsl:text>Съобщение за грешка</xsl:text>
														</span>
													</th>
													<td>
														<xsl:apply-templates/>
													</td>
												</tr>
											</tbody>
										</table>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:otherwise>
						</xsl:choose>
					</xsl:for-each>
				</xsl:for-each>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
