<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2008 rel. 2 sp1 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:bul="http://cais.mjs.bg/BulletinModel-v1.0" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:n1="http://cais.mjs.bg/PersonIdentifierSearchResponse-v1.0" xmlns:req="http://cais.mjs.bg/PersonIdentifierSearchRequest-v1.0" xmlns:xdt="http://www.w3.org/2005/xpath-datatypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:altova="http://www.altova.com">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.0 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:decimal-format name="format1" grouping-separator=" " decimal-separator=","/>
	<xsl:template match="/">
		<html>
			<head>
				<title/>
			</head>
			<body>
				<xsl:for-each select="$XML">
					<xsl:for-each select="n1:PersonIdentifierSearchResponse">
						<table style="border-collapse:collapse; " border="0" width="100%">
							<tbody>
								<tr>
									<td>
										<span style="font-weight:bold; ">
											<xsl:text>РЕПУБЛИКА БЪЛГАРИЯ</xsl:text>
										</span>
									</td>
									<td align="right">
										<span>
											<xsl:text>Дата на изготвяне: </xsl:text>
										</span>
										<xsl:for-each select="n1:ReportDate">
											<span style="font-weight:bold; ">
												<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
												<xsl:text>.</xsl:text>
												<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
												<xsl:text>.</xsl:text>
												<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
												<xsl:text> </xsl:text>
												<xsl:value-of select="format-number(number(substring(string(string(.)), 12, 2)), '00', 'format1')"/>
												<xsl:text>:</xsl:text>
												<xsl:value-of select="format-number(number(substring(string(string(.)), 15, 2)), '00', 'format1')"/>
											</span>
										</xsl:for-each>
									</td>
								</tr>
								<tr>
									<td>
										<span>
											<xsl:text>ЦАИС &quot;СЪДЕБЕН СТАТУС&quot;</xsl:text>
										</span>
									</td>
									<td align="right" height="20"/>
								</tr>
								<tr>
									<td align="center" colspan="2">
										<span>
											<xsl:text>ЕЛЕКТРОННА СПРАВКА ЗА ИДЕНТИФИКАТОР НА ЛИЦЕ</xsl:text>
										</span>
									</td>
								</tr>
								<tr>
									<td align="left" colspan="2" height="20">
										<xsl:choose>
											<xsl:when test="count( n1:ReportResult/bul:PersonData  )&gt;0">
												<span>
													<xsl:text>Приложени критерии за търсене: </xsl:text>
												</span>
												<xsl:for-each select="n1:ReportCriteria">
													<xsl:for-each select="req:Firstame">
														<div>
															<span>
																<xsl:text>Име: </xsl:text>
															</span>
															<span style="font-style:italic; ">
																<xsl:apply-templates/>
															</span>
														</div>
													</xsl:for-each>
													<xsl:for-each select="req:Surname">
														<div>
															<span>
																<xsl:text>Презиме: </xsl:text>
															</span>
															<span style="font-style:italic; ">
																<xsl:apply-templates/>
															</span>
														</div>
													</xsl:for-each>
													<xsl:for-each select="req:Familyname">
														<div>
															<span>
																<xsl:text>Фамилия: </xsl:text>
															</span>
															<span style="font-style:italic; ">
																<xsl:apply-templates/>
															</span>
														</div>
													</xsl:for-each>
													<xsl:for-each select="req:Fullname">
														<div>
															<span>
																<xsl:text>Пълно име: </xsl:text>
															</span>
															<span style="font-style:italic; ">
																<xsl:apply-templates/>
															</span>
														</div>
													</xsl:for-each>
													<xsl:for-each select="req:Birthdate">
														<div>
															<span>
																<xsl:text>Дата на раждане: </xsl:text>
															</span>
															<span style="font-style:italic; ">
																<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																<xsl:text>.</xsl:text>
																<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																<xsl:text>.</xsl:text>
																<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
															</span>
														</div>
													</xsl:for-each>
													<xsl:for-each select="req:BirthCountry">
														<div>
															<span>
																<xsl:text>Дъжава на раждане: </xsl:text>
															</span>
															<span style="font-style:italic; ">
																<xsl:apply-templates/>
															</span>
														</div>
													</xsl:for-each>
													<xsl:for-each select="req:Birthplace">
														<div>
															<span>
																<xsl:text>Място на раждане: </xsl:text>
															</span>
															<span style="font-style:italic; ">
																<xsl:apply-templates/>
															</span>
														</div>
													</xsl:for-each>
												</xsl:for-each>
												<xsl:for-each select="n1:ReportResult">
													<br/>
													<table style="border-collapse:collapse; " border="1">
														<thead>
															<tr>
																<th>
																	<span>
																		<xsl:text>И</xsl:text>
																	</span>
																	<span style="font-weight:bold; ">
																		<xsl:text>мена на кирилица</xsl:text>
																	</span>
																</th>
																<th>
																	<span style="font-weight:bold; ">
																		<xsl:text>Имена на латиница</xsl:text>
																	</span>
																</th>
																<th>
																	<span style="font-weight:bold; ">
																		<xsl:text>Пол</xsl:text>
																	</span>
																</th>
																<th>
																	<span style="font-weight:bold; ">
																		<xsl:text>Идентификатор/и</xsl:text>
																	</span>
																</th>
																<th>
																	<span style="font-weight:bold; ">
																		<xsl:text>Дата на раждане</xsl:text>
																	</span>
																</th>
																<th>
																	<span style="font-weight:bold; ">
																		<xsl:text>Място на раждане</xsl:text>
																	</span>
																</th>
																<th>
																	<span>
																		<xsl:text>Гражданство</xsl:text>
																	</span>
																</th>
																<th>
																	<span>
																		<xsl:text>Майка</xsl:text>
																	</span>
																</th>
																<th>
																	<span>
																		<xsl:text>Баща</xsl:text>
																	</span>
																</th>
																<th>
																	<span>
																		<xsl:text>AFIS</xsl:text>
																	</span>
																</th>
															</tr>
														</thead>
														<tbody>
															<xsl:for-each select="bul:PersonData">
																<tr>
																	<td>
																		<xsl:for-each select="bul:NamesBg">
																			<xsl:choose>
																				<xsl:when test="string-length(bul:FullName )=0">
																					<xsl:for-each select="bul:FirstName">
																						<span style="font-style:italic; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																					<xsl:for-each select="bul:SurName">
																						<span>
																							<xsl:text>&#160;</xsl:text>
																						</span>
																						<span style="font-style:italic; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																					<xsl:for-each select="bul:FamilyName">
																						<span>
																							<xsl:text>&#160;</xsl:text>
																						</span>
																						<span style="font-style:italic; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																				</xsl:when>
																				<xsl:otherwise>
																					<xsl:for-each select="bul:FullName">
																						<span style="font-style:italic; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																				</xsl:otherwise>
																			</xsl:choose>
																		</xsl:for-each>
																	</td>
																	<td>
																		<xsl:for-each select="bul:NamesEn">
																			<xsl:choose>
																				<xsl:when test="string-length(bul:FullName )=0">
																					<xsl:for-each select="bul:FirstName">
																						<span style="font-style:italic; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																					<xsl:for-each select="bul:SurName">
																						<span>
																							<xsl:text>&#160;</xsl:text>
																						</span>
																						<span style="font-style:italic; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																					<xsl:for-each select="bul:FamilyName">
																						<span>
																							<xsl:text>&#160;</xsl:text>
																						</span>
																						<span style="font-style:italic; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																				</xsl:when>
																				<xsl:otherwise>
																					<xsl:for-each select="bul:FullName">
																						<span style="font-style:italic; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																				</xsl:otherwise>
																			</xsl:choose>
																		</xsl:for-each>
																	</td>
																	<td>
																		<xsl:for-each select="bul:Sex">
																			<xsl:choose>
																				<xsl:when test=". =1">
																					<span style="font-style:italic; ">
																						<xsl:text>Мъж</xsl:text>
																					</span>
																				</xsl:when>
																				<xsl:when test=". =2">
																					<span style="font-style:italic; ">
																						<xsl:text>Жена</xsl:text>
																					</span>
																				</xsl:when>
																				<xsl:when test=". =0">
																					<span style="font-style:italic; ">
																						<xsl:text>Неизвестен</xsl:text>
																					</span>
																				</xsl:when>
																			</xsl:choose>
																		</xsl:for-each>
																	</td>
																	<td>
																		<xsl:for-each select="bul:IdentityNumber">
																			<xsl:for-each select="bul:EGN">
																				<div>
																					<span>
																						<xsl:text>ЕГН: </xsl:text>
																					</span>
																					<span style="font-style:italic; ">
																						<xsl:apply-templates/>
																					</span>
																					<span>
																						<xsl:text>&#160;</xsl:text>
																					</span>
																				</div>
																			</xsl:for-each>
																			<xsl:for-each select="bul:LN">
																				<div>
																					<span>
																						<xsl:text>ЛН: </xsl:text>
																					</span>
																					<span style="font-style:italic; ">
																						<xsl:apply-templates/>
																					</span>
																					<span>
																						<xsl:text>&#160;</xsl:text>
																					</span>
																				</div>
																			</xsl:for-each>
																			<xsl:for-each select="bul:LNCh">
																				<div>
																					<span>
																						<xsl:text>ЛНЧ: </xsl:text>
																					</span>
																					<span style="font-style:italic; ">
																						<xsl:apply-templates/>
																					</span>
																					<span>
																						<xsl:text>&#160;</xsl:text>
																					</span>
																				</div>
																			</xsl:for-each>
																			<xsl:for-each select="bul:SUID">
																				<div>
																					<span>
																						<xsl:text>Системно ID: </xsl:text>
																					</span>
																					<span style="font-style:italic; ">
																						<xsl:apply-templates/>
																					</span>
																					<span>
																						<xsl:text>&#160;</xsl:text>
																					</span>
																				</div>
																			</xsl:for-each>
																		</xsl:for-each>
																	</td>
																	<td align="left">
																		<xsl:for-each select="bul:BirthDate">
																			<xsl:for-each select="bul:DateMonthDay">
																				<xsl:for-each select="bul:DateDay">
																					<span style="font-style:italic; ">
																						<xsl:value-of select="format-number(number(substring(string(string(.)), 4, 2)), '00', 'format1')"/>
																					</span>
																					<span style="font-style:italic; ">
																						<xsl:text>.</xsl:text>
																					</span>
																				</xsl:for-each>
																				<xsl:for-each select="bul:DateMonth">
																					<span style="font-style:italic; ">
																						<xsl:value-of select="format-number(number(substring(string(string(.)), 3, 2)), '00', 'format1')"/>
																					</span>
																					<span style="font-style:italic; ">
																						<xsl:text>.</xsl:text>
																					</span>
																				</xsl:for-each>
																			</xsl:for-each>
																			<xsl:for-each select="bul:DateYear">
																				<span style="font-style:italic; ">
																					<xsl:apply-templates/>
																				</span>
																			</xsl:for-each>
																		</xsl:for-each>
																	</td>
																	<td align="left">
																		<xsl:for-each select="bul:BirthPlace">
																			<xsl:for-each select="bul:Country">
																				<xsl:for-each select="bul:CountryName">
																					<span style="font-style:italic; ">
																						<xsl:apply-templates/>
																					</span>
																				</xsl:for-each>
																			</xsl:for-each>
																			<xsl:for-each select="bul:City">
																				<xsl:for-each select="bul:CityName">
																					<span>
																						<xsl:text>, </xsl:text>
																					</span>
																					<span style="font-style:italic; ">
																						<xsl:apply-templates/>
																					</span>
																				</xsl:for-each>
																			</xsl:for-each>
																			<xsl:for-each select="bul:Descr">
																				<span>
																					<xsl:text>, </xsl:text>
																				</span>
																				<span style="font-style:italic; ">
																					<xsl:apply-templates/>
																				</span>
																			</xsl:for-each>
																		</xsl:for-each>
																	</td>
																	<td align="left">
																		<xsl:for-each select="bul:PersonNationality">
																			<xsl:for-each select="bul:CountryName">
																				<span style="font-style:italic; ">
																					<xsl:apply-templates/>
																				</span>
																			</xsl:for-each>
																			<xsl:for-each select="bul:CountryISOAlpha3">
																				<span>
																					<xsl:text> (</xsl:text>
																				</span>
																				<span style="font-style:italic; ">
																					<xsl:apply-templates/>
																				</span>
																				<span>
																					<xsl:text>); </xsl:text>
																				</span>
																			</xsl:for-each>
																		</xsl:for-each>
																	</td>
																	<td>
																		<xsl:for-each select="bul:MotherNames">
																			<xsl:choose>
																				<xsl:when test="string-length(bul:FullName )=0">
																					<xsl:for-each select="bul:FirstName">
																						<span style="font-style:italic; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																					<xsl:for-each select="bul:SurName">
																						<span>
																							<xsl:text>&#160;</xsl:text>
																						</span>
																						<span style="font-style:italic; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																					<xsl:for-each select="bul:FamilyName">
																						<span>
																							<xsl:text>&#160;</xsl:text>
																						</span>
																						<span style="font-style:italic; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																				</xsl:when>
																				<xsl:otherwise>
																					<xsl:for-each select="bul:FullName">
																						<span style="font-style:italic; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																				</xsl:otherwise>
																			</xsl:choose>
																		</xsl:for-each>
																	</td>
																	<td>
																		<xsl:for-each select="bul:FatherNames">
																			<xsl:choose>
																				<xsl:when test="string-length(bul:FullName )=0">
																					<xsl:for-each select="bul:FirstName">
																						<span style="font-style:italic; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																					<xsl:for-each select="bul:SurName">
																						<span>
																							<xsl:text>&#160;</xsl:text>
																						</span>
																						<span style="font-style:italic; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																					<xsl:for-each select="bul:FamilyName">
																						<span>
																							<xsl:text>&#160;</xsl:text>
																						</span>
																						<span style="font-style:italic; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																				</xsl:when>
																				<xsl:otherwise>
																					<xsl:for-each select="bul:FullName">
																						<span style="font-style:italic; ">
																							<xsl:apply-templates/>
																						</span>
																					</xsl:for-each>
																				</xsl:otherwise>
																			</xsl:choose>
																		</xsl:for-each>
																	</td>
																	<td>
																		<xsl:for-each select="bul:AFISNumber">
																			<span style="font-style:italic; ">
																				<xsl:apply-templates/>
																			</span>
																		</xsl:for-each>
																	</td>
																</tr>
															</xsl:for-each>
														</tbody>
													</table>
												</xsl:for-each>
											</xsl:when>
											<xsl:otherwise>
												<span>
													<xsl:text>УДОСТОВЕРЯВА, ЧЕ ЛИЦЕТО </xsl:text>
												</span>
												<xsl:for-each select="n1:ReportCriteria">
													<xsl:for-each select="req:Firstame">
														<div>
															<span>
																<xsl:text>Име: </xsl:text>
															</span>
															<xsl:apply-templates/>
														</div>
													</xsl:for-each>
													<xsl:for-each select="req:Surname">
														<div>
															<span>
																<xsl:text>Презиме: </xsl:text>
															</span>
															<xsl:apply-templates/>
														</div>
													</xsl:for-each>
													<xsl:for-each select="req:Familyname">
														<div>
															<span>
																<xsl:text>Фамилия: </xsl:text>
															</span>
															<xsl:apply-templates/>
														</div>
													</xsl:for-each>
													<xsl:for-each select="req:Fullname">
														<div>
															<span>
																<xsl:text>Пълно име: </xsl:text>
															</span>
															<xsl:apply-templates/>
														</div>
													</xsl:for-each>
													<xsl:for-each select="req:Birthdate">
														<div>
															<span>
																<xsl:text>Дата на раждане: </xsl:text>
															</span>
															<span>
																<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
																<xsl:text>.</xsl:text>
																<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
																<xsl:text>.</xsl:text>
																<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
															</span>
														</div>
													</xsl:for-each>
													<xsl:for-each select="req:BirthCountry">
														<div>
															<span>
																<xsl:text>Дъжава на раждане</xsl:text>
															</span>
															<xsl:apply-templates/>
														</div>
													</xsl:for-each>
													<xsl:for-each select="req:Birthplace">
														<div>
															<span>
																<xsl:text>Място на раждане: </xsl:text>
															</span>
															<xsl:apply-templates/>
														</div>
													</xsl:for-each>
												</xsl:for-each>
												<div style="text-align:center; ">
													<span>
														<xsl:text>НЕ Е ОСЪЖДАНО</xsl:text>
													</span>
												</div>
											</xsl:otherwise>
										</xsl:choose>
									</td>
								</tr>
								<tr>
									<td colspan="2">
										<xsl:for-each select="n1:ReportResult"/>
									</td>
								</tr>
							</tbody>
						</table>
					</xsl:for-each>
				</xsl:for-each>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
